### ISSUE TITLE
Subcription is not exported by node_modules/subscriptions-transport-ws/dist/index.js

### ISSUE THREAD

**Issue by frederikhors** [apollographql/apollo-link#1043]
I'm using https://github.com/sveltejs/template with rollup (https://github.com/sveltejs/template/blob/master/rollup.config.js).

During compile I get this error:
Error: "Subcription is not exported by node_modules/subscriptions-transport-ws/dist/index.js"

This I think I fixed with: 
https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports

```
		commonjs({
			namedExports: {
				// left-hand side can be an absolute path, a path
				// relative to the current directory, or the name
				// of a module in node_modules
				'./node_modules/subscriptions-transport-ws/dist/index.js': ['SubscriptionClient']
			}
		}),
```

Now it compiles but when I open site chrome says:
"Uncaught ReferenceError: events is not defined" in main.js

My component:
```
<script>
  import { getClient, subscribe } from 'svelte-apollo';
  import { SubscriptionClient } from "subscriptions-transport-ws";
  import { WebSocketLink } from "apollo-link-ws";
  import { CLIENT_SUBSCRIBE } from './data';
  import Showit from './Showit.html';
  const client = new SubscriptionClient("http://localhost:4000/graphql/", {
    reconnect: true
  });
  const link = new WebSocketLink(client);

  const new_books = subscribe(client, { query: CLIENT_SUBSCRIBE });
</script>

{#await $new_books}
    Waiting for new client...
  {:then result}
    New client: 
    <Showit model={result}/>
  {/await}
```

Showit.html

```
<script>
    export let model;
    console.log(model);
</script>
<div>
    <pre>{model}</pre>
</div>

```

_Originally posted by @jesperordrup in https://github.com/timhall/svelte-apollo/issues/10#issuecomment-491517274_

Rollup hates us novices.

**Is SubscriptionClient correctly exported and imported in apollo-link-ws?**

**Comment by JoviDeCroock** [comment]
I think this could be fixed by exporting an esm-compatible module build in that package.

**Comment by frederikhors** [comment]
Ah, ok. But I think that (great!) project needs `iife`. I don't know what `iife` means.

A reproduction: https://github.com/timhall/svelte-apollo/tree/master/example

- rollup.config.js:

```js
import svelte from 'rollup-plugin-svelte';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import replace from 'rollup-plugin-replace';

export default {
  input: 'src/main.js',
  output: {
    sourcemap: true,
    format: 'iife',
    name: 'app',
    file: 'public/bundle.js',
    globals: {
      'apollo-boost': ''
    }
  },
  external: [],
  plugins: [
    svelte({
      dev: true,
      css: css => {
        css.write('public/bundle.css');
      }
    }),
    resolve(),
    commonjs(),
    replace({
      'process.env.NODE_ENV': JSON.stringify('development')
    })
  ]
};
```

How do you think we can fix?

Is there a fix importing `SubscriptionClient` correctly in `apollo-link-ws`?

**Comment by JoviDeCroock** [comment]
The thing is the package you are talking about is exporting a CJS build:
https://unpkg.com/subscriptions-transport-ws@0.9.16/dist/client.js

If you add a `module` build that should be fixed. Same goes for for example React, if you want to use an export in React it will also need to be included in that plugin.

You could try if pointing to /browser works but I think the better solution would be to include the proper build instead of only a UMD/CJS one. Umd being the one in /browser and CJS in /dist

**Comment by frederikhors** [comment]
Oh my. I'm lost.

What would you do to make everything work with github.com/svelte/template?

**Comment by JoviDeCroock** [comment]
It does work, it just needs a helping hand (you help it out by specifying it in your `commonjs` rollup attribute), also I think this is better discussed on their repository instead of ours.

**Comment by JoviDeCroock** [comment]
If this throws in apollo-link-ws feel free to reopen it but this feels like an issue with the transport-ws.

If you however can point me to a stacktrace of one of these repositories throwing I’d be more than happy to further explore this.

**Comment by frederikhors** [comment]
@JoviDeCroock thanks for your help. I created a simple repo: https://codesandbox.io/s/zn1mnon8jl.

If you open it in codesandbox it works! But if you download as a zip and execute `npm i && npm run dev` you can see the problem.

Can I help you helping me more?

**Comment by JoviDeCroock** [comment]
Well as I said it works when adding it:

```
    commonjs({
      namedExports: {
        'node_modules/subscriptions-transport-ws/dist/index.js': ['SubscriptionClient']
      }
    }),
```

This means that `apollo-link-ws` imports the CJS build from `transport-ws` but rollup can't handle this very well. This would improve if they would export a build like that.

Else you should as above clarify to rollup that it is exported. The apollo-link-ws repository can't change anything to make this easier on you as far as I know.

**Comment by frederikhors** [comment]
Ok. thanks I'm starting to better understand.

If I add what you say the error now becomes:

```log
index.js → public/bundle.js...
(!) Mixing named and default exports
Consumers of your bundle will have to use bundle['default'] to access the default export, which may not be what you want. Use `output.exports: 'named'` to disable this warning
(!) Missing shims for Node.js built-ins
Creating a browser bundle that depends on 'events', 'https', 'http', 'url', 'zlib' and 'stream'. You might need to include https://www.npmjs.com/package/rollup-plugin-node-builtins
(!) Unresolved dependencies
https://rollupjs.org/guide/en#warning-treating-module-as-external-dependency
events (imported by node_modules\ws\lib\websocket.js, node_modules\ws\lib\websocket-server.js,  commonjs-external-events)
crypto (imported by node_modules\ws\lib\websocket.js, node_modules\ws\lib\websocket-server.js, node_modules\ws\lib\sender.js,  commonjs-external-crypto)
https (imported by node_modules\ws\lib\websocket.js,  commonjs-external-https)
net (imported by node_modules\ws\lib\websocket.js,  commonjs-external-net)
http (imported by node_modules\ws\lib\websocket.js, node_modules\ws\lib\websocket-server.js,  commonjs-external-http)
tls (imported by node_modules\ws\lib\websocket.js,  commonjs-external-tls)
url (imported by node_modules\ws\lib\websocket.js, node_modules\ws\lib\websocket-server.js,  commonjs-external-url)
stream (imported by node_modules\ws\lib\receiver.js,  commonjs-external-stream)
zlib (imported by node_modules\ws\lib\permessage-deflate.js,  commonjs-external-zlib)
bufferutil (imported by node_modules\ws\lib\buffer-util.js,  commonjs-external-bufferutil)
utf-8-validate (imported by node_modules\ws\lib\validation.js,  commonjs-external-utf-8-validate)
(!) Missing global variable names
Use output.globals to specify browser global variable names corresponding to external modules
events (guessing 'events')
crypto (guessing 'crypto')
https (guessing 'https')
http (guessing 'http')
net (guessing 'net')
tls (guessing 'tls')
url (guessing 'url')
zlib (guessing 'zlib')
bufferutil (guessing 'bufferutil')
stream (guessing 'stream')
utf-8-validate (guessing 'utf8Validate')
created public/bundle.js in 13.8s
```

What a mess. I'm using just web oriented libraries, why it complains about nodejs dependencies?

**What to do now?**

I think `apollo-link-s` or `subscriptions-transport-ws` should write a wiki/FAQ about rollup.

**Comment by JoviDeCroock** [comment]
This is something that is explained in the rollup docs (which is also present in your stack there)

**Comment by frederikhors** [comment]
Yes, but since I'm building a web app why it complains about node.js dependencies?

**Comment by frederikhors** [comment]
> Though the issue now seems to be that events is undefined.

Yes, it's hard for newbies.

If you fix it I can open a PR for a wiki/FAQ page.

**Comment by frederikhors** [comment]
I added these in `rollup.config.js`:

```js
import builtins from 'rollup-plugin-node-builtins'
import globals from 'rollup-plugin-node-globals'
...
plugins: [
  globals(),
  builtins(),
```

and all the previous errors are gone.

Now in browser I got:

```log
Uncaught ReferenceError: exports is not defined
    at client.js:45
```

It complains about this line (I think):

`Object.defineProperty(exports, "__esModule", { value: true });`

**Comment by frederikhors** [comment]
I opened a SO question to recap: https://stackoverflow.com/questions/56167898/rollup-and-subscriptions-transport-ws

**Comment by frederikhors** [comment]
Some people have made a simil-fork package to solve the Rollup problem temporarily: https://github.com/lunchboxer/graphql-subscriptions-client.
