### ISSUE TITLE
Unable to omit content-type http header with apollo-link-http

### ISSUE THREAD

**Issue by schpet** [apollographql/apollo-link#1122]
Hi,

I'm interested in an httpLink without including any `Content-Type` headers so that I can use 
```
<link rel="preload" href="/graphql?query=query..."  as="fetch" type="application/json" crossorigin>
```

to pre-load this query as described in [“Making Instagram.com faster: Part 1”](https://instagram-engineering.com/making-instagram-com-faster-part-1-62cc0c327538)

```
  const httpLink = createHttpLink({
    uri: GRAPHQL_URL,
    fetch: fetch,
    useGETForQueries: true,
    headers: {},
  })
```

**Expected Behavior**

requests made with this httpLink to not have a `Content-Type`

**Actual Behavior**

requests made with this httpLink to have a `Content-Type: application/json`

**A _simple_ reproduction**

I... am sorry, I don't have one. It's because of this merge strategy though:

https://github.com/apollographql/apollo-link/blob/c32e170b72ae1a94cea1c633f977d2dbfcada0e1/packages/apollo-link-http-common/src/index.ts#L219-L222

and changing it like this works for me:
https://github.com/schpet/apollo-link/commit/70a64c804e9719668efd480466f6c4f8b7bf976a

but i'm worried this is not a backwards compatible change. maybe something like

```
  const httpLink = createHttpLink({
    uri: GRAPHQL_URL,
    fetch: fetch,
    useGETForQueries: true,
    headers: {
      'content-type': undefined,
    }
  })
```

and then stripping out undefined values could work better. or maybe this is a job for a custom link.

**Comment by schpet** [comment]
after some digging, i think what's needed is to remove the `Content-Type` header from GET requests only, which i think should be a safe change since GETs don't have a body.

**Comment by mlc** [comment]
I think this may be a dup of #539.
