### ISSUE TITLE
Invariant violation: 1 – Run apollo client with node.js

### ISSUE THREAD

**Issue by Jones-S** [apollographql/apollo-link#1125]
**Expected Behavior**
Make a connection to my endpoint and return data for my query.

**Actual Behavior**
Throwing an error:
>  FATAL  Invariant Violation: 1 (see https://github.com/apollographql/invariant-packages)                                                                                                         14:50:43

>  Invariant Violation: Invariant Violation: 1 (see https://github.com/apollographql/invariant-packages)
  at new InvariantError (packages/.../node_modules/ts-invariant/lib/invariant.js:16:28)
  at new ApolloClient (packages/.../node_modules/apollo-client/bundle.umd.js:2483:55)
  at generateRoutesFromData (packages/.../src/routes/generateRoutesFromData.js:49:18)
  at Object.<anonymous> (nuxt.config.js:158:10)
  at Generator.next (<anonymous>)

**A _simple_ reproduction**
Run the following code in node.js (Version v10.16.0)
I am absolutely sure that the token and the API endpoint are correct, because I got the same connection up and running with Nuxt + Apollo (https://github.com/nuxt-community/apollo-module).

```javascript
    import gql from 'graphql-tag'
    import { ApolloClient } from 'apollo-client'
    import { createHttpLink } from 'apollo-link-http'
    import { setContext } from 'apollo-link-context'
    // Tried all sorts of fetch polyfills - none of them worked.
    // import('whatwg-fetch')
    // import { fetch } from 'whatwg-fetch'
    // import fetch from 'node-fetch-polyfill'
    import fetch from 'isomorphic-fetch'
    // import 'whatwg-fetch'
    // import 'cross-fetch/polyfill'

    export default function generateRoutesFromData() {
      const uri = 'https://example.com/api'
      const token =
        '...MY-TOKEN...XZfPsvY...'

      const httpLink = createHttpLink({ uri, fetch })

      const authLink = setContext((_, { headers }) => {
        // return the headers to the context so httpLink can read them
        return {
          headers: {
            ...headers,
            authorization: `Bearer ${token}`
          }
        }
      })


      // for now just using the most basic query to exclude errors here...
      const GET_PAGES = gql`
        {
          helloWorld
        }
      `

      const client = new ApolloClient({
        link: authLink.concat(httpLink)
      })

      client
        .query({
          query: GET_PAGES
        })
        .then(result => {
          console.log('result: ', result)
        })
        .catch(error => {
          console.log('error: ', error)
        })
    }


```

I read in different places that this obscure error has to do with fetch missing within HttpLink.
If I don't import fetch on top, I will get the following error message.

>  FATAL                                                                                                                                                                                           14:58:42
fetch is not found globally and no fetcher passed, to fix pass a fetch for
your environment like https://www.npmjs.com/package/node-fetch.

> For example:
import fetch from 'node-fetch';
import { createHttpLink } from 'apollo-link-http';

> const link = createHttpLink({ uri: '/graphql', fetch: fetch });

  > Invariant Violation:
  fetch is not found globally and no fetcher passed, to fix pass a fetch for
  your environment like https://www.npmjs.com/package/node-fetch.
  
  > For example:
  import fetch from 'node-fetch';
  import { createHttpLink } from 'apollo-link-http';
  
Following these instructions will get me to the error mentioned above, with much less information what the error could have caused...

Unfortunately I am lost and can't find any working examples to run an apollo request against an endpoint within node.js...

I do realize there is this other ticket:
https://github.com/apollographql/apollo-link/issues/1025
But as I said, using `isomorphic-fetch` does not solve my issue either.

Also all these solutions:
https://stackoverflow.com/questions/50688998/using-apolloclient-with-node-js-fetch-is-not-found-globally-and-no-fetcher-pas
Did not work...

So some pointers would be much appreciated.

Cheers

J

**Comment by JoviDeCroock** [comment]
Your crash is due to you not initializing your client correctly, you forgot your `cache` option.

**Comment by Jones-S** [comment]
Thanks. 🙈 
I think I need to get to understand the basics a bit more... It works.
