### ISSUE TITLE
Question: Is this implementation of apollo-network-interface?

### ISSUE THREAD

**Issue by pronevich** [apollographql/apollo-link#12]
Looks like network interface implementation described [here](https://github.com/apollographql/apollo-network-interface/tree/master/src) . Pluggable + observables and etc. I am just noticed that "standard interface for modifying control flow" not obvious for me at first sight.

**Comment by jbaxleyiii** [comment]
@pronevich the goal of links it to replace the network interface. Currently (via 1.9.0-1), Apollo Client supports using links as a network interface. We plan on writing about how they work together and what it means for the future of Apollo soon!

**Comment by jbaxleyiii** [comment]
@pronevich also, thank you for the question!
