### ISSUE TITLE
Error in doc

### ISSUE THREAD

**Issue by jay1337** [apollographql/apollo-link#123]
In

```
const httpLink = createHttpLink({ uri: '/graphql' });
const errorLink = onError(({ networkError }) => {
  if (networkError.status === 401) {
    logout();
  }
})
```

`networkError.status` must be replaced by `networkError.response.status` or `networkError.statusCode`

**Comment by jay1337** [comment]
In fact the type of `networkError` should be:
```
type ResponseError = Error & {
  response?: Response;
  parseError: Error;
  statusCode?: number;
};
```
But:

1. `parseError` is some time undefined (e.g. if the server does not respond)
2. `statusCode` is not defined even if `networkError.response.status` is a valid status code

**Comment by jbaxleyiii** [comment]
Ah thanks! I think we should fix a couple of these and update the docs!

**Comment by jbaxleyiii** [comment]
Fixed via https://github.com/apollographql/apollo-link/pull/144

**Comment by jay1337** [comment]
@jbaxleyiii thanks !
