### ISSUE TITLE
Documentation example with graphiql and simple HttpLink does not work

### ISSUE THREAD

**Issue by PCreations** [apollographql/apollo-link#124]
**Intended outcome:**

I just wanted to test a simple graphiql implementation by directly taking the example from the doc

**Actual outcome:**

An error is triggered by graphql for any request, telling that the node isn't a valid `AST Node`. It's easy to understand why, the `execute` method exported by `apollo-link` expect the `operation` object to be a `Operation` type but graphiql only send an object with the printed query as the query parameters. I have to edit the snippet to look like this instead to make it work :
```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import '../node_modules/graphiql/graphiql.css'
import GraphiQL from 'graphiql';

import gql from 'graphql-tag';
import { execute } from 'apollo-link';
import { HttpLink } from 'apollo-link-http';
import { parse } from 'graphql';

const link = new HttpLink({
  uri: '/graphql'
});

ReactDOM.render(
  <GraphiQL fetcher={
    (operation) => execute(link, {
      ...operation,
      query: parse(operation.query),
    })}
  />,
  document.getElementById('root'),
);

```

**How to reproduce the issue:**

Just clone and `yarn && yarn start` this repo :  https://github.com/PCreations/example-apollo-link-graphiql

**Comment by jbaxleyiii** [comment]
@PCreations thanks for this! I think we could also create a super simple `parseLink` which handles this for you! Would you be open to working on that?

**Comment by PCreations** [comment]
@jbaxleyiii Sure ! Maybe we should just define the specs for this link before, on slack ? on this issue ?

**Comment by jbaxleyiii** [comment]
Lets do it here 👍

**Comment by PCreations** [comment]
As far as I understrand, this link should be responsible to parse the given operation. So we could use it with GraphiQL as such : 
```javascript
const link = ApolloLink.from([
  new ParseLink(),
  new HttpLink({
    uri: '/graphql',
  }),
]);
<GraphiQL fetcher={
    (operation) => execute(link, operation)
  }
  />,
```

**Comment by jbaxleyiii** [comment]
yep! And it should just run `parse(query)` and pass that forward to the next link:

```js
const parser = new ApolloLink((operation, forward) => {
  operation.query = typeof operation.query === 'string' ? parse(operation.query) : operation.query;
  return forward(operation);
})
```

**Comment by JoviDeCroock** [comment]
Since this issue is really outdated I am closing it but if you are still concerned about this feel free to reopen and I'll get back to you asap.
