### ISSUE TITLE
[question] what version should I be using to test out apollo 2 beta?

### ISSUE THREAD

**Issue by stefanmaric** [apollographql/apollo-link#126]
Hi!

I'm trying Apollo v2 beta.

I see these releases: https://github.com/apollographql/apollo-link/commit/adf6806f6bbc95e2f60b58b0e3886e883fe6b93b

But those are published under the `latest` and not the `beta` dist-tag.

Are the tags wrong?

**Comment by jbaxleyiii** [comment]
The links should be used with the `latest` tag 🎉
