### ISSUE TITLE
apollo-link-error should provide more context to the error handler

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-link#127]
The apollo-link-error onError ErrorHandler would be more useful if it received the operation, and maybe some more parts of the result if available.

**Comment by nevir** [comment]
👍 

Our use case: We generate a UUID for each request, include it as a request-id header, but also need access to it when reporting errors

**Comment by stubailo** [comment]
Yeah it should probably receive basically everything!

**Comment by jbaxleyiii** [comment]
on it!

**Comment by jbaxleyiii** [comment]
Fixed via https://github.com/apollographql/apollo-link/pull/144 🎉
