### ISSUE TITLE
ApolloLink.from doesn't work with custom links

### ISSUE THREAD

**Issue by jchavarri** [apollographql/apollo-link#133]
In `0.7.0`, when using `ApolloLink.from` with a custom made link, the `(operation, forward) => ...` callback is not called.

**Intended outcome:**
After reading the [docs](https://github.com/apollographql/apollo-link/pull/81/files#diff-f69b272afefed3280218e5739b60ff1eR28):
> `from` is typically used when you have many links to join together all at once. The alternative way to join links is the `concat` method which joins two links together into one.

I was expecting I could implement my own `authLink` and the operations could be forwarded like with `concat`.

**Actual outcome:**
The custom link forwarding callback is never called.

**How to reproduce the issue:**
Create a custom link and then join it with an Apollo Link using `from`:

```js
import { HttpLink } from 'apollo-link-http';
...
const logLink = new ApolloLink((operation, forward) => {
  return forward(operation).map((data) => {
    console.log('logging');
    return forward(operation);
  })
});
const link = ApolloLink.from([
   new HttpLink({ uri }),
   logLink,
]);
const client = new ApolloClient({
  cache: new InMemoryCache()
  link,
});
// `logging` will never be printed
```

**Comment by jchavarri** [comment]
Hm, my bad, seems `logLink` has to go first :)

**Comment by jonasdumas** [comment]
Thanks, it solve 2 hours of debbuging !
The httplink need to go at the end when use from()
HM!
