### ISSUE TITLE
apollo-link-error should have the ability to suppress propagation of the error

### ISSUE THREAD

**Issue by jamesreggio** [apollographql/apollo-link#140]
Some of our error handlers are capable of 'handling' the error, and should be able to stop the propagation of the error to downstream observers.

At present, when an error is handled, we just strip out the `errors` array on the response before forwarding it on. This isn't particularly elegant, but it works.

Perhaps a solution could fit nicely within the request/response context you plan to include with #127.

**Comment by jbaxleyiii** [comment]
@jamesreggio so the idea here is to remove the errors from making it back to other links / apollo-client?

**Comment by jbaxleyiii** [comment]
I think this is pretty easy GraphQLErrors, but stopping a thrown / network error would leave the observable hung and unable to ever return to the client.

**Comment by jbaxleyiii** [comment]
Will be possible via https://github.com/apollographql/apollo-link/pull/144
