### ISSUE TITLE
apollo-link-error should use consistent naming convention

### ISSUE THREAD

**Issue by jamesreggio** [apollographql/apollo-link#141]
Quite simply, `apollo-client` will attach GraphQL errors to an exception under the key [`graphQLErrors`](https://github.com/apollographql/apollo-client/blob/9b0a587b9d5d94016d6fcb27db8d6e8d0ae1ff93/packages/apollo-client/src/errors/ApolloError.ts#L47), but `apollo-link-error` provides them to the callback under the key `graphqlErrors`.

(I have some common logic that depends upon the former naming convention, and it took me a little while to figure out why it wasn't working. Capitalization is a pain to identify.)

**Comment by jbaxleyiii** [comment]
Absolutely! On it!

**Comment by jbaxleyiii** [comment]
Fixed via https://github.com/apollographql/apollo-link/pull/144
