### ISSUE TITLE
Error on jest tests

### ISSUE THREAD

**Issue by Poincare** [apollographql/apollo-link#142]
There's an error on running `npm run test` on a freshly cloned repository. 

**Intended outcome:**
Attempted to run the tests and it should run the tests.

**Actual outcome:**
Get this error:

```
(node:32245) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Command
failed: npm run test
● Validation Error:

  Module <rootDir>/node_modules/ts-jest/preprocessor.js in the transform option was not found.

  Configuration Documentation:
  https://facebook.github.io/jest/docs/configuration.html
```

**How to reproduce the issue:**
Create a freshly cloned repository in a fresh node environment and attempt to run the tests.

Please note: I am not familiar with Jest - there may be a set up step that I'm currently missing?

**Comment by Poincare** [comment]
Ah, I see that the solution to this problem is to run `npm install` within each sub-package and then run `npm test` (as opposed to `npm install` on the top-level).

I think this is probably pretty obvious to most people - should we document it anyway (maybe in the README.md or a CONTRIBUTORS.md) in case somebody else hits this?

**Comment by jbaxleyiii** [comment]
@Poincare yeah that's no good! You have to run `npm bootstrap` to get everything up and running! I'll document this!
