### ISSUE TITLE
dedup is not working with apollo-link-batch-http

### ISSUE THREAD

**Issue by seeden** [apollographql/apollo-link#157]
I can see in one request same queries with same variables. These queries are batched because I am using apollo-link-batch-http. Without it I will see 2 same requests.
Are you going to add dedup for batched requests as well?

![Queries](https://i.imgur.com/UWMGJ6N.png)

Currently I am using:
```
    link: ApolloLink.from([
      retryLink,
      headersLink,
      dedupLink,
      httpLink,
    ]),
```

```
    "apollo-cache-inmemory": "^0.2.0-rc.1",
    "apollo-client": "^2.0.0-rc.3",
    "apollo-link": "^0.8.0",
    "apollo-link-http": "^0.8.0",
    "apollo-link-batch-http": "^0.4.0",
    "apollo-link-retry": "^0.8.0",
    "apollo-link-dedup": "^0.6.0",
```

**Comment by tiffwu** [comment]
I'm having the same issue.

**Comment by gdi2290** [comment]
I'm also having the same issue.

**Comment by kaelumania** [comment]
same issue here

**Comment by gdi2290** [comment]
I have a fork of `apollo-link-batch-http` that combines the logic with `apollo-link-dedup`

`npm install --save @tipe/apollo-dedup-batch-http-link`

the options are the same as both combined
🎉 🎉
cc @tiffwu @kaelumania @seeden

**Comment by smeijer** [comment]
@gdi2290, sounds awesome. But wouldn't it be possible to submit an PR to fix the issue? Instead of creating a package with the same functionality?

**Comment by gdi2290** [comment]
@smeijer I believe they're making batching a default feature which is why they're not fixing this until that's done (a lot of internal changes)

**Comment by JoviDeCroock** [comment]
Since this issue is really outdated I am closing it but if you are still concerned about this feel free to reopen and I'll get back to you asap.
