### ISSUE TITLE
@types/zen-observable

### ISSUE THREAD

**Issue by sheeldotme** [apollographql/apollo-link#163]
I understand why @types/zen-observable is listed as a dev dependency for the apollo-link package, however this may not be ideal as it may cause confusion for some when they cannot build.

As we know, dev dependencies are not transitive, and as such, downstream users utilizing typescript are left having to know to install @types/zen-observable or have their builds fail.

I'll leave this open ended as to a resolution as there are a range of solutions (dependencies, optional dependencies, peer dependencies, better documentation) that may address this better.  Thoughts?

**Intended outcome:**
Expected all necessary files for a typescript build to be installed, so `tsc` would result in a successful build.

**Actual outcome:**
`tsc` results in error TS2688: Cannot find type definition file for 'zen-observable'.

**How to reproduce the issue:**
Add the `apollo-link` node module, build using `tsc`

**Comment by alvis** [comment]
@sheeldotme  is correct. All dependent definitions should be tagged as a dependency rather than a dev dependency. See https://github.com/Microsoft/types-publisher/issues/81. Otherwise, it won't be installed and therefore type script would complain.

Just made a PR #171
