### ISSUE TITLE
apollo-link-http loses contents of error responses from apollo-server

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-link#178]
[`apollo-server` turns any response with `error` and no `data` into a 400](https://github.com/apollographql/apollo-server/blob/c9b8ef9d2495f2088c2e1c51c7f1f6234abaca97/packages/apollo-server-core/src/runHttpQuery.ts#L144-L148).  An easy way to trigger such a response is to ask for a field that doesn't exist, eg `query { xxxx }`.

[`apollo-link-http` turns that into an error which doesn't actually have the JSON on it](https://github.com/apollographql/apollo-link/blob/cdb2a5ec2629cef1c56f96eab226c38528aff846/packages/apollo-link-http/src/httpLink.ts#L21-L24).

It does put the response on the error, but the JSON was already read so you can't re-read it from the response.

Also, it puts an error describing the fact that this was a 400 response onto the thus-misleadingly-named `parseError` field.

This is the root cause behind [errors showing up in the devtools as `[object Object]`]: apollographql/apollo-client-devtools#81

apollo-link-http should make the contents of the error available to its clients even if it's on a 400, as long as JSON parses properly.  Or perhaps apollo-server should not make these errors return 400. I'm not sure.

**Comment by oliviertassinari** [comment]
> apollo-link-http should make the contents of the error available to its clients even if it's on a 400, as long as JSON parses properly.

This! 👍 I'm getting a `Error: body used already for` error when trying to read the response a second time `networkError.response.text()`.

**Comment by jbaxleyiii** [comment]
@evans did this get changed with your error PR? Can you take a look?

**Comment by evans** [comment]
Yeah this should be solved with #244. On a network error(>= 300 status), the parsed body of the response will be the `result` field of the error.

We also removed `parseError`.

CC @glasser
