### ISSUE TITLE
Usage for async middleware not properly written.

### ISSUE THREAD

**Issue by shahzeb1** [apollographql/apollo-link#188]
Within the [usage section in the docs](https://github.com/apollographql/apollo-link/blob/5fbaaf47e5ff1189d65ee674f09fbda464c23d5a/packages/apollo-link-context/README.md#usage) the following code doesn't seem to be compiling anywhere:

```js
const asyncMiddleware = setContext((request) => new Promise(success, fail) => {
  // do some async lookup here
  setTimeout(() => {
    success({ token: 'async found token' })
  }, 10);
});
```

Am i doing something wrong is the syntax for this little code chunk incorrect?

**Comment by n1ru4l** [comment]
@shahzeb1 The code example is incorrect, the correct code can be found here: https://github.com/apollographql/apollo-link/pull/191/files

**Comment by shahzeb1** [comment]
Ah thank you. A minor problem, but glad it's taken care of.
