### ISSUE TITLE
FetchOptions has no property uri

### ISSUE THREAD

**Issue by corydeppen** [apollographql/apollo-link#189]
**Intended outcome:**
No compilation errors.

**Actual outcome:**
Get a TS error `TS2459: Type 'FetchOptions | undefined' has no property 'uri' and no string index signature` when compiling a simple CRA app.

**How to reproduce the issue:**
Using `apollo-link-http@1.0.0`, I have the following code to create an `ApolloClient`:

```ts
const client = new ApolloClient({
  cache: new InMemoryCache(),
  // causes an error when compiled
  link: createHttpLink({ uri: 'http://localhost:4000/graphql' })
  // works fine
  // link: new HttpLink({ uri: 'http://localhost:4000/graphql' })
});
```

It's very strange and I don't see anything obviously wrong with the declaration file (`/path/to/node_modules/apollo-link-http/lib/httpLink.d.ts`) that would cause this. What makes it more odd is that it seems to only happen the first time it's compiled, but if I make a change that forces a recompilation it will typically build without a problem. I'm wondering if anyone else has seen this before or could think of what might be causing it.

**Comment by Grmiade** [comment]
https://github.com/Microsoft/TypeScript/issues/19029 🤔

**Comment by Grmiade** [comment]
The problem is this line `export declare const createHttpLink: ({uri, fetch: fetcher, includeExtensions, ...requestOptions}?: FetchOptions) => ApolloLink;`.
We can't extract a `uri` field if the param can be undefined (**?**).
We should refactor this line by `export declare const createHttpLink: (options?: FetchOptions) => ApolloLink;` maybe. We don't need to extract options params here.

**Comment by Grmiade** [comment]
Any news?

**Comment by corydeppen** [comment]
I'm no longer seeing this issue using `apollo-link-http@1.2.0`. Can someone else confirm?

**Comment by Grmiade** [comment]
I still have this problem :/
If you try to `rm -rf node_modules` and `npm install`. It's always fixed?

**Comment by corydeppen** [comment]
Yeah, I started from a clean `node_modules` directory. The only things I had to manually tweak were the fix for the [`lodash.flowright` issue](https://github.com/apollographql/react-apollo/issues/1286) in `react-apollo` and setting `"strictNullChecks": false` in `tsconfig.json` to get around the [return type issue](https://github.com/apollographql/apollo-client/issues/2503) in `apollo-client`. Running `yarn outdated` confirms all packages are current.

**Comment by Grmiade** [comment]
`strictNullChecks: false`allow to fix this issue too I think. Because our issue is we can’t extract an explicit field from an undefined parameter.

**Comment by corydeppen** [comment]
By moving the destructuring out of the parameter into the body of `createHttpLink`, the declaration output from `tsc` looks more appropriate and it runs without error.

```ts
// httpLink.ts
export const createHttpLink = (options?: FetchOptions) => {
  let { uri, fetch: fetcher, includeExtensions, ...requestOptions } = options;
  // ...
};

// httpLink.d.ts
export declare const createHttpLink: (options?: FetchOptions) => ApolloLink;
```

**Comment by jbaxleyiii** [comment]
hmmm, I'm happy to merge and release that PR but that should certainly be valid typescript and not show that error. If the changes work though I'm happy with it!

**Comment by evans** [comment]
Thank you for the fix!
