### ISSUE TITLE
Bump version with fix for zen-observable?

### ISSUE THREAD

**Issue by arahansen** [apollographql/apollo-link#19]
The current release on npm for apollo-link is leading to issues with my builds that can't handle zen-observable's src.

apollo-link in this case is actually a dependency of the library I'm using, apollo-client

Would it be possible to get a quick patch to npm that has the fix in place?

My current workaround right now is to run zen-observable through my a babel-loader with webpack.

related PR: https://github.com/apollographql/apollo-link/pull/18

**Comment by arahansen** [comment]
also, I just realized that PR was merged only an hour ago! I hope I don't come across as impatient. My workaround works pretty well for my use case for the time being.

**Comment by evanshauser** [comment]
@arahansen can you post an error log from your build?

Thank you for posting so quickly!

**Comment by arahansen** [comment]
The error was essentially UglifyJS from webpack trying to parse es6 code because apollo-link was consuming it directly.

It was failing on this line: https://github.com/zenparsing/zen-observable/blob/master/src/Observable.js#L19

**Comment by evanshauser** [comment]
@arahansen got it I manually published. Lerna seemed not to pick up `apollo-link` even though it created the tag. The build should run now

**Comment by evanshauser** [comment]
@arahansen Still failing. Working on a typescript implementation of zen-observable, since I don't think there is an easier way of getting rid of the git dependency #14 and keeping the typings.

Please let me know if you have other ideas

**Comment by evanshauser** [comment]
Fixed with #23
