### ISSUE TITLE
Getting 400 error when POST-ing via mutation.

### ISSUE THREAD

**Issue by shahzeb1** [apollographql/apollo-link#193]
**Intended outcome:**

Should be able to POST the mutation to the GraphQL server (located at AWS Lambda).

**Actual outcome:**

![image](https://user-images.githubusercontent.com/1383831/32206989-1550ec32-bdb6-11e7-9a03-05014d02f90d.png)
Gives the following issue: `there was an error sending the query Error: Network error: Network request failed with status 400 - ""`

**How to reproduce the issue:**

In my main controller: 
```js
const httpLink = createHttpLink({ uri: 'https://xxx.execute-api.us-west-2.amazonaws.com/dev/graphql' });

let token;
const withToken = setContext(() => {
  if (token) return { token };
  const tok = localStorage.getItem('id_token') || null;
  token = tok;
  return { Authorization: `Bearer ${token}` };
});

const link = withToken.concat(httpLink);

const client = new ApolloClient({
  link,
  cache: new InMemoryCache()
});

const handleAuthentication = (nextState, replace) => {
  if (/access_token|id_token|error/.test(nextState.location.hash)) {
    auth.handleAuthentication();
  }
};
```

Within the `buttonPressed()` function:
```js
        this.props.newEnvMutation({
            variables: {
              identityId: id,
              title: name,
            }
          })
          .then(({ data }) => {
            console.log('got data', data);
          })
          .catch(error => {
            console.log('there was an error sending the query', error);
          });
```

**Comment by shahzeb1** [comment]
Got it to work: 
There was an error with the actual query. 

I still think it's a little strange that an error with the query (a mismatch in the variables that were being sent vs. the values given to the variables) shouldn't produce an HTTP error. Even though I'm logging everything at the apollo-lambda layer, it didn't catch anything strange either.

**Comment by evans** [comment]
Thank you for opening the issue! Glad to hear you resolved it. If you can think of any documentation changes that could make this easier for others to understand, please open a PR.
