### ISSUE TITLE
Please move `@types/zen-observable` from devDependencies to dependencies

### ISSUE THREAD

**Issue by foisonocean** [apollographql/apollo-link#199]
I'm getting this error while I'm using Typescript with strict mode:
```
node_modules/apollo-link/lib/index.d.ts(4,29): error TS7016: Could not find a declaration file for module 'zen-observable'. '/Users/hronro/Projects/klbb/node_modules/zen-observable/index.js' implicitly has an 'any' type.
  Try `npm install @types/zen-observable` if it exists or add a new declaration (.d.ts) file containing `declare module 'zen-observable';`
node_modules/apollo-link/lib/link.d.ts(1,23): error TS2688: Cannot find type definition file for 'zen-observable'.
```
Move `@types/zen-observable` from devDependencies to dependencies will solve that problem.

**Comment by Grmiade** [comment]
Any news?

**Comment by jbaxleyiii** [comment]
@foisonocean @Grmiade or anyone else want to open a PR for this? It be a great first contribution!

**Comment by Grmiade** [comment]
This issue is fixed for me. Indeed,`@types/zen-observable` seems be a dependencies.
https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link/package.json#L44

**Comment by evans** [comment]
Thank you @alvis for #171!

**Comment by plinionaves** [comment]
Did not work for me... :(

I had to go in my "node_modules/@types/zen-observable/index.d.ts" and add this to the end of the file:

`export default Observable;`

Why?

Note: I replaced this:
`export = Observable`
By the line mecioned above
