### ISSUE TITLE
Feature Idea: Automatic name aliasing / re-mangling ex: snake_case -> camelCase

### ISSUE THREAD

**Issue by fbartho** [apollographql/apollo-link#209]
Many backends have a `snake_case` convention for JSON responses. Conversely, it looks like many GraphQL endpoints have a camelCase convention. When taking `apollo-link-rest` into consideration, our Client-side `@rest` directives need to have a way to normalize field-keys anyhow to deal with whatever responses they are likely to return.

Example problematic response
```json
{
  "this_is_ruby_json_convention": true,
  "this is unconventional but legal json": true,
  "this_responseHasSome_weirdly_named_fields": true,
  "THIS_LOOKS_LIKE_SCREAMING": true,
  "          ": "this one is problematic too"
}
```

Feature Idea: add a spot where users can hook in their own property name renormalization code. An example normalizer might strip/replace symbols that aren't valid identifiers. Another example normalizer might reformat all of those into camelCase.

**Comment by jbaxleyiii** [comment]
👍 this is now part of the design spec for apollo-link-rest!
