### ISSUE TITLE
[docs] Logo not found

### ISSUE THREAD

**Issue by lucasconstantino** [apollographql/apollo-link#213]
The logo on the documentation seems to be unavailable. Here is a screenshot and URL:

http://apollo-link-docs.netlify.com/docs/link/

![screenshot from 2017-11-05 20 01 08](https://user-images.githubusercontent.com/2688512/32419651-8e356d00-c264-11e7-827e-3d9030e57593.png)

**Comment by jbaxleyiii** [comment]
@lucasconstantino thanks so much! We are working to update this!

cc @nicseo

**Comment by evans** [comment]
This should be fixed now!
