### ISSUE TITLE
React Native, building for release, "fetch is not found globally and no fetcher passed"

### ISSUE THREAD

**Issue by kimf** [apollographql/apollo-link#220]
**Intended outcome:**
Building a RN app for release using apollo-link-http and have it work.

**Actual outcome:**
```
Unhandled JS Exception: fetch is not found globally and no fetcher passed, to fix pass a fetch for
      your environment like https://www.npmjs.com/package/node-fetch.
...
```

**How to reproduce the issue:**
Unfortunately no easy way to test this without building the RN app.
Created a new RN app with the same error and pushed that to here: 

https://github.com/kimf/apollo-link-global-fetch-bugreport-repro

Adding a simple `fetch()` call works, so fetch is available globally.
I've tried to confirm that this is not a RN issue as well.

**Comment by kimf** [comment]
I upgraded RN to 0.50.3, and this issue was solved.
Really strange because I could not find a single change in the new release that should have affected this. 
Closing this as it is not an issue anymore, sorry for taking up your time :)

**Comment by albinekb** [comment]
I can reproduce this error in my code and in your example 😭

**Comment by donedgardo** [comment]
I'm having this issue too
