### ISSUE TITLE
apollo-link-http does not respect a GET method override

### ISSUE THREAD

**Issue by szdc** [apollographql/apollo-link#236]
As per the [docs](https://www.apollographql.com/docs/link/links/http.html#Context), the `fetchOptions` option allows us to set the method of the request to `GET`.  I'd expect that after doing so, the query would be included as a query string parameter rather than the request body; Chrome throws an error if you try to make a GET request with a body.

**Intended outcome:**
A query string should be constructed if the request method is GET.

**Actual outcome:**
The request body is used.

**How to reproduce the issue:**
```javascript
client.query({
  context: {
    fetchOptions: {
      method: 'GET',
    },
  },
  query: QUERY,
  variables: { query },
})
```

**Comment by jbaxleyiii** [comment]
@szdc yep this definitely doesn't work! Would you be open to adding it? Something like https://github.com/apollographql/apollo-link/issues/257 may be a good solution as well to transform the request before its sent?

**Comment by arackaf** [comment]
I'll add it if nobody else wants to.

**Comment by jbaxleyiii** [comment]
@szdc @arackaf so turns out this is already possible! I'll push up a test and docs soon showing how it can be done without internal changes

**Comment by jbaxleyiii** [comment]
@szdc @Outlaw11A @arackaf here is how to do it:

```js
const customFetch = (uri, options) => {
  const { body, ...newOptions } = options;
  const queryString = objectToQuery(JSON.parse(body));
  requestedString = uri + queryString;
  return fetch(requestedString, newOptions);
};
const link = createHttpLink({
  uri: "data",
  fetchOptions: { method: "GET" },
  fetch: customFetch
});

```

**Comment by arackaf** [comment]
@jbaxleyiii that looks awesome!  Just curious from where objectToQuery is coming?  Is there a util on npm for that?  I imagine it'd be pretty easy to just roll your own if needed - basically map Object.keys onto `escapeUriComponnt(`${k}=${obj[k]}).join("&");`

**Comment by johnunclesam** [comment]
https://www.apollographql.com/docs/link/links/http.html#Sending-GET-requests-custom-fetching

**Comment by johnunclesam** [comment]
@jbaxleyiii it works! It's amazing!

I just have a problem.

The querystring created:

`http://localhost/graphql?operationName=AllPlayersQuery&variables=%5Bobject%20Object%5D&query=query%20All...`

contains this: `variables=%5Bobject%20Object%5D` which is a problem.

How to fix this?

**Comment by arackaf** [comment]
That looks like standard URI serialization - don't think you can avoid it - why's it a problem?

**Comment by johnunclesam** [comment]
Standard URI? This: `%5Bobject%20Object%5D`?

**Comment by arackaf** [comment]
encodeURIComponent('books(title:"Hello World"){Book{title}}')

`books(title%3A%22Hello%20World%22)%7BBook%7Btitle%7D%7D`

**Comment by johnunclesam** [comment]
My query in Apollo is:

```
query AllPlayers {
  players {
    id
    name
    surname
}
```

and so I have the problem with `[Object object]` variables empty with the code posted by @jbaxleyiii.

**Comment by ianserlin** [comment]
Here's a barebones react app (created using create-react-app) that fetches via GET and works - see `index.js`: https://github.com/usefulio/example-graphql-via-get-react-app

**Comment by fallafeljan** [comment]
@johnunclesam obviously `variables` isn't serialized before encoding. i simply tuned my custom fetch method (obtained from the example repo) by adding a conditional `JSON.stringify`:

```
const customFetch = (uri, options) => {
  const {body, ...newOptions} = options;
  const parsedBody = JSON.parse(body);
  const command = omitBy(parsedBody, isEmpty);

  if (command.variables) {
    command.variables = JSON.stringify(command.variables);
  }

  const requestedString = uri + '?' + queryString.stringify(command);

  return fetch(requestedString, newOptions);
};
```

**Comment by ivawzh** [comment]
So what is `useGETForQueries` used for? Why the custom fetch is not builtin when `useGETForQueries=true`?
How do I differentiate query and mutation? I only want to use GET for query (for DNS cache).

**Comment by glasser** [comment]
This is an old issue that predates useGETForQueries, which was added a bit after this was fixed by https://github.com/apollographql/apollo-link/pull/510

**Comment by jharris4** [comment]
umm, useGETForQueries seems to not be working.

Specifically on this line there seems to be a bug:

https://github.com/apollographql/apollo-link/blob/f94b1c6b984619ec1ef68cca3224be788ea140e4/packages/apollo-link-http/src/httpLink.ts#L41

```
let {
    uri = '/graphql',
    // use default global fetch if nothing passed in
    fetch: fetcher,
    includeExtensions,
    useGETForQueries,
    ...requestOptions
  } = linkOptions;
```

should be something like:

```
let {
    uri = '/graphql',
    // use default global fetch if nothing passed in
    fetch: fetcher,
    includeExtensions,
    fetchOptions,
    ...requestOptions
  } = linkOptions;

let {
  useGETForQueries
} = fetchOptions;

```

**Comment by glasser** [comment]
What makes you say that? How are you calling `createHttpLink`?

**Comment by jharris4** [comment]
My observation above was from stepping through the code with a debugger, but I'd have to do it over again to reproduce.

The code we ended up settling on is this:

```
import omitBy from 'lodash.omitby';
import isEmpty from 'lodash.isempty';

const graphQLUrl = 'http://the.server.com/graphql';

const customFetch = (uri, options) => {
  const { body, credentials, headers, ...newOptions } = options;
  let fetchUri = uri;
  if (body) {
    const parsedBody = JSON.parse(body);
    const command = omitBy(parsedBody, isEmpty);
    fetchUri = uri + "?" + queryString.stringify(command);
  }
  return fetch(fetchUri, newOptions);
};

const link = createHttpLink({
  uri: graphQLUrl,
  fetchOptions: { method: "GET" },
  fetch: customFetch
});
```

**Comment by glasser** [comment]
I guess my question is, if you were passing `useGETForQueries` inside `fetchOptions` instead of directly inside `createHttpLink`, then that would be the behavior you would observe, but it would also not be how the API works. I'd suggest giving it a shot again!
