### ISSUE TITLE
Missing changelog entries for apollo-link

### ISSUE THREAD

**Issue by jaydenseric** [apollographql/apollo-link#237]
The `apollo-link` package [changelog](https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link/CHANGELOG.md) only has 3 entries, the last two being `0.8.0` and `vNEXT`. The are in fact 24 published versions, the most recent being `1.0.1`:

```
npm view apollo-link versions --json
```
```json
[
  "0.0.0",
  "0.0.1",
  "0.0.2",
  "0.0.3",
  "0.1.0",
  "0.1.1",
  "0.2.0",
  "0.3.0",
  "0.3.1",
  "0.4.0",
  "0.4.1",
  "0.5.0",
  "0.5.2",
  "0.5.4",
  "0.6.1-beta.0",
  "0.6.1-beta.1",
  "0.6.1-beta.3",
  "0.6.1-beta.4",
  "0.6.1-beta.5",
  "0.6.1-beta.6",
  "0.7.0",
  "0.8.0",
  "1.0.0",
  "1.0.1"
]
```

**Comment by jaydenseric** [comment]
Adding to the frustration, none of the Github releases have descriptions:

<img width="468" alt="screen shot 2017-11-13 at 10 52 30 am" src="https://user-images.githubusercontent.com/1754873/32704885-dfbf968a-c860-11e7-97b8-8c796ff6a715.png">

**Comment by jaydenseric** [comment]
While we're at it, the git branches and tags could do with a cleanup:

<img width="323" alt="screen shot 2017-11-13 at 10 57 36 am" src="https://user-images.githubusercontent.com/1754873/32704931-adc3cff6-c861-11e7-9576-a77db33fcafa.png">

**Comment by jbaxleyiii** [comment]
@jaydenseric I've tried to go back and add as much of this as I could. The problem right now has to do with how lerna commits and does releases (including things like package.json changes causing a "release")

I know this is frustrating and I'm working on a better release solution, if you have any ideas, I'd love to hear them! Ideally we need to improve this for all our lerna repos

**Comment by evans** [comment]
Looks like we fixed up the Changelog. Thank you James!

Now we'll have to look at cleaning up the branches and linking up the git tags. Help is welcome!
