### ISSUE TITLE
Feature idea: Allow string or function `uri` option for HttpLink

### ISSUE THREAD

**Issue by stephenkao** [apollographql/apollo-link#264]
Hey, there!  

I'm currently upgrading from apollo-client@1.9.0 to apollo-client@2.0.1, and I'm running into a slight issue since HTTPFetchNetworkInterface was removed.  Originally, I had something like the following (based on [this issue](https://github.com/apollographql/apollo-client/issues/1267)): 

```jsx
import { HTTPFetchNetworkInterface } from 'apollo-client';

export class CustomApolloNetworkInterface extends HTTPFetchNetworkInterface {
  fetchFromRemoteEndpoint({ request, options }) {
    const { _uri } = this;
    const { operationName } = request;
    if (operationName) this._uri += `?opname=${operationName}`;

    const requestPromise = super.fetchFromRemoteEndpoint({ request, options });
    this._uri = _uri;

    return requestPromise;
  }
}

export default function createApolloClient() {
  const networkInterface = new CustomApolloNetworkInterface(`${url}/graph/graphql`);
  return new ApolloClient({ networkInterface });
}
```

This let me add the operation name as a query parameter to each request, which I used for automated alerting and graphing based on operation timings.  Since the custom network interface is no longer around, this is slightly more difficult.

My proposal is to make the `uri` option for HttpLink to be opened up to a function as well as a string.  [The actual fetch](https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-http/src/httpLink.ts#L178) would turn out to be something like:

```jsx
let uriValue = typeof uri === 'function' ? uri(operation) : uri;  // do a safer function validation here :P
fetcher(contextURI || uriValue, fetcherOptions).then(() => { ... });
```

That'd allow for something like:
```jsx
export default function createApolloClient() {
  const link = new HttpLink({
    uri: (operation) => `${url}/graph/graphql?opname=${operation.operationName}`
  });

  const client = new ApolloClient({
    link,
    cache: new InMemoryCache().restore(IS_BROWSER ? window.__APOLLO_STATE__ : {}),
  });

  return client;
}
```

What do y'all think?  If there's a better way to do this, please let me know!  Thanks!

**Comment by jbaxleyiii** [comment]
@stephenkao this is super interesting! One way you can do it is with the `context` key during an operation. So if you are using just the client `client.query({ query, context: { uri: /* my generated uri */ } })` or if using `graphql` from react-apollo: `graphql(QUERY, { options: { context: { uri: /* my generated uri */ }})`

**Comment by jbaxleyiii** [comment]
@Ingibjorg I'd be open to the API described in the original issue with a PR!

**Comment by stephenkao** [comment]
Fantastic!  I'm working a pull request now.  :)

**Comment by jbaxleyiii** [comment]
done and merged! :yay:!

**Comment by jbaxleyiii** [comment]
@stephenkao so after a couple other issues, I realized this was already possible!

```js
const customFetch = (uri, options) => {
  const { operationName } = JSON.parse(options.body);
  return fetch(`${uri}/graph/graphql?opname=${operationName}`, options);
};

const link = createHttpLink({ fetch: customFetch });
```

I've reverted the change [here](https://github.com/apollographql/apollo-link/pull/286) which also keeps the library under the 4kb threshold. Is this okay to you?

Thank you so much for bringing this issue up and the work on the PR, I really appreciate it and it helped to solve 3 other issues without adding anything else to the library!

**Comment by stephenkao** [comment]
@jbaxleyiii Yeah, this looks fantastic!  Thank you so much for following up on this.

**Comment by eug48** [comment]
@jbaxleyiii  Adding the `operationNames` to the querystring is really valuable for metrics/analytics but I'm not thrilled with having to do a JSON.parse in the customFetch.. especially on tablets making large queries..

What about having HttpLink & BatchHttpLink simply pass the body object as a non-standard option to the fetcher? (e.g. in `apolloRequestBody`)

Another option is to make `serializeFetchParameter` customisable - it could then do a no-op and leave the JSON.stringify to the custom fetcher.

Thanks!

**Comment by SyscoMssApolloEngine** [comment]
You can use this instead of JSON.parse

const httpLink = createHttpLink({ uri: ({ operationName }) => {
  return `${uri}/${operationName}`;
} });

**Comment by starting** [comment]
Following works for me. 

const httpLink = createHttpLink({ uri: ({ operationName }) => {
  return `${uri}/${operationName}`;
} });
