### ISSUE TITLE
Headers passed to server are just serialized string "headers":"[object Object]"

### ISSUE THREAD

**Issue by jinglemansweep** [apollographql/apollo-link#265]
**Intended outcome:**

I'm trying to pass additional headers (such as authorisation), but when I inspect the headers sent (in the browser) and also headers received (by the server), all I see is what appears to be a serialized string interpretation of the object (e.g. [object Object]).

**Actual outcome:**

I'd expect the headers object to be an actual object which I can extract values from, instead it appears to be a string interpretation of an object.

**How to reproduce the issue:**

**Comment by jbaxleyiii** [comment]
@jinglemansweep we don't stringify headers? https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-http/src/httpLink.ts#L173 Can you reproduce this for me?

**Comment by jinglemansweep** [comment]
This was user error on my part. Closing the issue.
