### ISSUE TITLE
SyntaxError: Unexpected token import in linkUtils.js:19 when running Jest

### ISSUE THREAD

**Issue by andrei-anisimov** [apollographql/apollo-link#269]
Running jest tests throws an error, because apollo-link/lib/linkUtils.js have import statements in the JS code. We're importing `createOperation`. Any idea how to solve this?

I created a package to implement a custom link. I took the apollo-link-http folder, left the configuration as is and simply implemented my link. In my code I use the following import:
```
import { createOperation } from "apollo-link/lib/linkUtils";
```

**Actual outcome:**
When I run `npm run test` it throws the following error:

```
    /Users/andreianisimov/projects/8base/file-server-sdk/node_modules/apollo-link/lib/linkUtils.js:19
    import { getOperationName } from 'apollo-utilities';
    ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
      at Object.<anonymous> (src/TokenRefreshLink.ts:14:44)
      at Object.<anonymous> (test/TokenRefreshLink.test.ts:2:25)
```

**How to reproduce the issue:**
1. Copy any apollo-link-* package and add `import "apollo-link/lib/linkUtils"` somewhere. 
2. Run `npm run test`

**Comment by jbaxleyiii** [comment]
@andrei-anisimov hmm I'm not sure! But a better solution would be to export `createOperation` from the utils as part of the main exports, then you can just import it from ApolloLink package.

**Comment by andrei-anisimov** [comment]
@jbaxleyiii I agree, that would be the right solution. Any plans to do this in the near future?

**Comment by andrei-anisimov** [comment]
`createOperation` was added to exports. The problem is solved, thanks! Closing.

**Comment by stevensacks** [comment]
Still happening for me. I can't test my app.

```
FAIL  src/index.test.js
  ● Test suite failed to run

    /Users/steven/Development/frontend/node_modules/apollo-link-context/lib/index.js:10
    import { ApolloLink, Observable, } from 'apollo-link';
    ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Object.<anonymous> (src/main.js:11:12)
      at Object.<anonymous> (src/index.test.js:1:203)```

**Comment by jaridwarren** [comment]
Did you ever find a solution?
