### ISSUE TITLE
Content-type isn't application/json

### ISSUE THREAD

**Issue by renatomefi** [apollographql/apollo-link#275]
**Intended outcome:**
Header to be:
```
Content-Type:application/json
```

**Actual outcome:**
```
Content-Type:text/plain;charset=UTF-8
```

My link configuration:
```javascript
        const link  = new HttpLink({
            uri: 'http://127.0.0.1:8000',
            fetchOptions: {
                mode: 'no-cors'
            }
        });

        const cache = new InMemoryCache();

        this.client = new ApolloClient({
            link,
            cache
        });
```

NPM Packages:
```json
{
  "name": "to-do",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "apollo-cache-inmemory": "^1.1.1",
    "apollo-client": "^2.0.3",
    "apollo-fetch": "^0.6.0",
    "apollo-link-http": "^1.1.0",
    "graphql": "^0.11.7",
    "graphql-tag": "^2.5.0",
    "loadash": "^1.0.0",
    "react": "^16.1.1",
    "react-apollo": "^2.0.1",
    "react-dom": "^16.1.1",
    "react-scripts": "1.0.17"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

**Comment by renatomefi** [comment]
It seems to happen when you use `no-cors`, even trying to force the header in the fetch options doesn't work

**Comment by jbaxleyiii** [comment]
@renatomefi could this have something to do with `fetch`? In testing I can't replicate this https://github.com/apollographql/apollo-link/pull/283/commits/1201f135ed478ef11b4be2b12f21cd95c55d03cd

**Comment by renatomefi** [comment]
@jbaxleyiii Indeed, looks like it's a fetch issue :/

**Comment by jbaxleyiii** [comment]
well that stinks!

**Comment by rohmanhm** [comment]
I run into this problem. Any solution for this issue?

![image](https://user-images.githubusercontent.com/7524911/34705533-9dd7e7cc-f533-11e7-97f0-183a010564b9.png)

**Comment by joaovpmamede** [comment]
@jbaxleyiii I don't think your PR fixed this issue, still sends `Content-Type: text/plain;charset=UTF-8`.

**Comment by renatomefi** [comment]
@joaovpmamede the PR was about testing on apollo-link level, the problem exists inside fetch

**Comment by ais-one** [comment]
so need to ask fetch to fix this first before it can work?

**Comment by mousssaab** [comment]
Hi @jbaxleyiii,
i have the same problem, i can't change the header contant-type i use angular1-apollo and i try to applyMiddleware to change header for all request. can you help me please

**Comment by ais-one** [comment]
Why does fetch behave this way? Even though it is a fetch problem, I think this issue should still be open unless a solution is reached or a work-around is found for this, because this is going to kill your adoption rate.

**Comment by pencilcheck** [comment]
Still having this issue, really annoying...

**Comment by rohmanhm** [comment]
The simplest solution is to use `no-cors` middleware library to your backend.
This works really well for me.

**Comment by andrao** [comment]
Hi everyone – I've found a solution, at least in Express:

Express **app.js**:
```js
const bodyParser = require('body-parser');

// ...

app.use('/graphql', bodyParser.text());
app.use('/graphql', (req, res, next) => {
    if(typeof req.body === 'string')
        req.body = JSON.parse(req.body);

    next();
});
```
- `bodyParser.text()` will append the `text/plain` to `req.body`

---
React **index.js**:
```js
new HttpLink({
    // ...
    fetchOptions: {
        mode: 'no-cors'
    }
});
```

**Comment by cmcaboy** [comment]
@andrao your solution worked for me. Thank you.

**Comment by quakig** [comment]
Any solutions for this ? This issue has been closed but no fix has been provided.
I still get this as my `Content-Type` :

`Content-Type:` text/plain;charset=UTF-8

**Comment by phillip055** [comment]
+1

**Comment by fga8** [comment]
+1

**Comment by dixitnikhil** [comment]
> I run into this problem. Any solution for this one?
> 
> ![image](https://user-images.githubusercontent.com/7524911/34705533-9dd7e7cc-f533-11e7-97f0-183a010564b9.png)

Did anyone find solution to this? Is it possible to have content-type application/json in request headers when using no-cors?

**Comment by techieanant** [comment]
I came across this issue while implementing Apollo client for my React application. The way I was able to fix it was follow @rohmanhm 's advice and use cors library for node to handle this on my express/graphql endpoint. 

So my Apollo client request looks like this after I remove no-cors fetchOptions: 

`
const client = new ApolloClient({
  uri: 'http://localhost:4000/graphql'
})
`

And added this code to express server.js 

```
const cors = require('cors')
app.use('*', cors())  
app.use('/graphql', bodyParser.json(), graphqlExpress(buildOptions))
```
Hope this helps.

**Comment by DNature** [comment]
Please is there a way to solve this?. files content-type returns text/html.
![error](https://user-images.githubusercontent.com/49137104/69246285-b8bc9780-0ba8-11ea-8694-0c089230195c.png)

**Comment by tslocke** [comment]
In case anyone hits this with a similar situation to me (dev on localhost), i.e. 

- React dev server running on localhost:3000
- GraphQL server running on localhost:8888 (or whatever - a different port)

You can solve this by adding `"proxy": "http://localhost:8888"` to package.json

Then you can just connect to "/graphql" or whatever the API endpoint is, and drop the no-cors option.

TIL!
