### ISSUE TITLE
[RetryLink] Simplify by merging delay & interval?

### ISSUE THREAD

**Issue by nevir** [apollographql/apollo-link#301]
Today, `RetryLink` accepts `delay` and `interval` configuration properties, which seem to have overlapping concerns:

`interval` computes the number of milliseconds until the next retry should begin, and is given the output of `delay`, along with the retry count.  `delay` is only used to determine the input for `interval`, and is given the operation as input.

---

Suggestion, merge them into a single configuration property (`delay` is probably the right name, but maybe something different for backwards compatibility?):

`delay: (operation, count) => ms`

@evans I'm curious what the initial intention was behind the split there?  Am I missing some cases?

**Comment by jbaxleyiii** [comment]
@nevir yep those should be merged together and I think `delay` is the right call API name wise. If you want to include this in #311 or into it, we can just go to `2.0` and not worry about backwards compat
