### ISSUE TITLE
Overriding the api url dynamically in the latest version

### ISSUE THREAD

**Issue by vvaldersteins** [apollographql/apollo-link#305]
Hi,

I was wondering if it's possible to override the API url dynamically in the latest version of the apollo-graphql?

In the old version it was possible to do it, by simply overriding the _uri parameter of networkInterface, but the latest version has slight changes, and this is not possible anymore.

`networkInterface._uri = 'new-api-url'`

Is there any possibility to do something similar in the latest version?

If more information is required, please let me know.

Best regards,
Valters

**Comment by jbaxleyiii** [comment]
@vvaldersteins it is! There are a couple ways to it actually. First is by using `uri` on the context of the request [more info at this link](https://www.apollographql.com/docs/link/links/http.html#Context) or you can calculate it if you want by the operation [like is shown here](https://www.apollographql.com/docs/link/links/http.html#Sending-GET-requests-custom-fetching)
