### ISSUE TITLE
apollo-link-retry: Duplicate queries are discarded

### ISSUE THREAD

**Issue by davidblurton** [apollographql/apollo-link#318]
apollo-link-retry keys queries using `operation.toKey()` but this isn't unique. The client then deduplicates the queries which results in some requests being dropped, even if the query isn't retried. 

To reproduce: Create a component that calls a query and include that component twice in the same page. One of the component won't receive any results if the retry link is present. 

The key should probably be a unique id instead. I'm happy to make a PR if you approve the approach.

**Comment by davidblurton** [comment]
Ok, looks like we can't change the query key because the dedup link assume the same key...

**Comment by davidblurton** [comment]
I tried disabling the deduplicate like this but it didn't have any effect. 

```
setContext((request, previousContext) => ({
  ...previousContext,
  forceFetch: true,
}));
```

**Comment by davidblurton** [comment]
Full example: 

I have a DatePicker component that loads some timezone info. If I include this component twice and I also include the retry-link, the second one doesn't rerender when the timezone query resolves. If I remove the retry-link, both components are rendered. 
```
const Picker = ({data}) => ...

const DatePickerQuery = gql`
  query DatePickerQuery($timezone: String!) {
    timezone(zone: $timezone) {
      utcOffset
    }
  }
`;

export default graphql(DatePickerQuery)(Picker);
```

**Comment by nevir** [comment]
I think #311 will resolve this for ya

**Comment by jbaxleyiii** [comment]
@davidblurton @nevir is correct! His changes (total rewrite) will make it work much better! I'm release the 2.0 of retry-link today which will clear this up for you!
