### ISSUE TITLE
zen-observable-ts contains source-map references which are not included

### ISSUE THREAD

**Issue by swernerx** [apollographql/apollo-link#32]
**Intended outcome:**

Webpack source map loader should work. It tries to find the relevant source files by looking up references in the source maps.

This seems to affect other apollo-packages as well.

**Actual outcome:**

The source map does not seem to contain the source file content. Therefor the loader tries to lookup the files - which are not included in the npm package.

Throws the following errors when used in Webpack:

<img width="1041" alt="bildschirmfoto 2017-08-04 um 08 07 49" src="https://user-images.githubusercontent.com/145201/28956260-0dc7d9bc-78ec-11e7-999c-f8d005acb99f.png">

See also: https://github.com/webpack-contrib/source-map-loader/issues/18

**How to reproduce the issue:**

Set-up a small Webpack project and add the source-map-loader to the configuration:

```js
    module: {
      rules: [
        {
          test: /\.(js|mjs|jsx)$/,
          use: [ "source-map-loader" ],
          enforce: "pre"
        },

        ...
      ]
    }
```

**Comment by evanshauser** [comment]
@swernerx Thank you for filling an issue! You are correct that `zen-observable-tx` has a source map issue. As do all of the links! I think we will do something similar to [apollo-fetch](https://github.com/apollographql/apollo-fetch/pull/9) to break up the test tsconfig.json and deploy/ have a base tscofing in the root.

@kamilkisiela do you have the bandwidth to setup rollup and the tsconfig structure for Apollo Link?

**Comment by jbaxleyiii** [comment]
This is done!
