### ISSUE TITLE
Docs: Example at bottom of dedup-link README doesn't actually use dedup-link

### ISSUE THREAD

**Issue by dlee** [apollographql/apollo-link#326]
Example at bottom of dedup-link README doesn't actually use dedup-link.

http://apollo-link-docs.netlify.com/docs/link/links/dedup.html#Context
https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-dedup/README.md

**Comment by nandito** [comment]
The doc says:

> NOTE This link is included by default when using apollo-client so you don’t need to add it to your link chain if using apollo-client.

So as the example of the Context section uses Apollo Client, I think it also uses the dedup-link under the hood. And that can be overridden by using `forceFetch` in the query context.

**Comment by evans** [comment]
@nandito this is a great point! Thank you for bringing it up. Could you open a PR to add the note about apollo-client including the link by default? ... the extra context as it were 😆

**Comment by nandito** [comment]
@evans sure, I can.

But the note I quoted in my previous comment is already on that page. I'm not sure if it's a good idea to put the same note twice to there. Would you like me to move that note from the top of the docs to the Context section?

For me the current state seems more straightforward but I'm open for improvement ideas 🙂

**Comment by JoviDeCroock** [comment]
The top states that this is included by default, the bottom tells how to override this default behavior. I think it's worth closing this issue, if there are more questions about this feel free to ask.
