### ISSUE TITLE
Batching and credentials with apollo-link-batch-http

### ISSUE THREAD

**Issue by KROT47** [apollographql/apollo-link#343]
What about intuitive API for BatchHttpLink like the one in [example](https://www.apollographql.com/docs/react/basics/network-layer.html#) of HttpLink?

Seems to me it should look similar with BatchHttpLink to prevent dumb errors:
```js
import ApolloClient from 'apollo-client';
import { BatchHttpLink } from 'apollo-link-batch-http';

const batchLink = new BatchHttpLink({
  uri: 'https://example.com/graphql',
  // Additional fetch options like `credentials` or `headers`
  credentials: 'same-origin',
});

const client = new ApolloClient({
  batchLink,
  // other options like cache
});
```

**Comment by seangransee** [comment]
Came here looking for this. Looks like it's already planned. From the [Batch Http Link docs](https://www.apollographql.com/docs/link/links/batch-http.html):

> Note: This package will be updated to remove the dependency on apollo-fetch an use the same options / API as the http-link

**Comment by evans** [comment]
We are planning to move batching into `apollo-link-http`. If you have any comments, please add them to #364!

That means that batching will use the same credentials settings as a single request.
