### ISSUE TITLE
SchemaLink incorrectly expects an execution return value to be a `Promise`

### ISSUE THREAD

**Issue by brabeji** [apollographql/apollo-link#351]
Hello! I think I've found a bug:

**Intended outcome:**
Being able to obtain synchronous result from SchemaLink

**Actual outcome:**
SchemaLink incorrectly expects `graphql`'s `execute` to always returns a `Promise`. In case of synchronous execution an Error is thrown.

**How to reproduce the issue:**
https://codesandbox.io/s/jjmk3jwyl3

I think this may be consequence of incorrect `graphql` API Reference: https://github.com/graphql/graphql.github.io/pull/439

Cheers and big thank you for this awesome library!

**Comment by Neitsch** [comment]
I'm not familiar enough with this project to fix it myself, but it looks like it just needs to be wrapped in a Promise.resolve graphql/graphql-js#1115

**Comment by stubailo** [comment]
Yeah this is a breaking change in `graphql@0.12`, it used to always return a promise.

Mind sending a PR to always wrap it in a resolve?

**Comment by brabeji** [comment]
This was fixed by #354. Closing.
