### ISSUE TITLE
Not loading on Internet Explorer

### ISSUE THREAD

**Issue by elie222** [apollographql/apollo-link#357]
We're getting the following error for our IE users and stops the entire page loading for them:
`fetch is not found globally and no fetcher passed`.

We hope this will fix it:
```
import fetch from 'node-fetch';
        import { createHttpLink } from 'apollo-link-http';

        const link = createHttpLink({ uri: '/graphql', fetch: fetch });
```

Will update shortly if that worked.

**Comment by elie222** [comment]
Sorry, `node-fetch` is node only. Will need another polyfill.

**Comment by stubailo** [comment]
Yeah, in the docs we recommend `unfetch`: https://www.apollographql.com/docs/link/links/http.html#fetch

Was it hard to find that documentation? How can we make this more visible?

**Comment by elie222** [comment]
Great. See it now. I just did the update and our site is working for IE
users again. I used isomorphic fetch. Any issues using that? Or a reason to
prefer unfetch?

When looking for this issue I searched for Internet Explorer in both this
github repo and the Apollo Client repo. Hopefully others that run into this
in the future find the issue I opened. It may be worth adding the words
Internet Explorer explicitly to the docs.

Also, is there a reason you decided not to include this by default? Enough
people still use IE. We had 2 users complain to us about the site not
working within a day or so of using Apollo 2.

**Comment by stubailo** [comment]
Nope, isomorphic fetch is just fine!

> Also, is there a reason you decided not to include this by default? Enough people still use IE.

This was one of the breaking changes in 2.0, but I think we might not have communicated it well. I think the conclusion was that the overwhelming majority of browsers include `fetch` and that we could document the polyfill. It's good to know that didn't quite come across, and I'll make sure I add it to the upgrade guide right now.

Maybe we can have a section called "browser compatibility" somewhere, like the Apollo Client docs.

**Comment by uvadoug2** [comment]
Could you post a working example?  I have tried both unfetch and isomorphic fetch and still cannot get it working.

**Comment by AmauryLiet** [comment]
@stubailo I would recommend adding a eye-catching "warning" mention and/or icon.
I guess the title "Fetch polyfill" isn't catchy enough for someone trying to have the simplest working configuration.

**Comment by JoviDeCroock** [comment]
Since this issue is really outdated I am closing it but if you are still concerned about this feel free to reopen and I'll get back to you asap.
