### ISSUE TITLE
Reading Headers With Afterware

### ISSUE THREAD

**Issue by NicholasLYang** [apollographql/apollo-link#373]
I'm looking to add afterware that takes the headers from a query and adds them to localstorage. Right now I'm finding a lot of the opposite; middleware taking a token from localstorage and adding it to a query. Anybody have experience with using headers in afterware? Thanks

**Comment by agborkowski** [comment]
its solved, you have to update to apollo-link "apollo-link": "^1.0.7", and use code like 

https://github.com/benawad/slack-clone-client/blob/31_fix_auto_refresh_of_jwt_tokens/src/apollo.js#L18

but still we have issue with https://github.com/apollographql/apollo-angular/tree/master/packages/apollo-angular-link-http in response i see headers from request only

**Comment by ash0080** [comment]
I can get response headers, but
any chance to pass the headers out?  
for example to the query response?

I tried, but not work

**Comment by evans** [comment]
Thank you @agborkowski for the links!

@ash0080 you can add them to the response before returning them from the `map` call, for example [here](https://github.com/benawad/slack-clone-client/blob/31_fix_auto_refresh_of_jwt_tokens/src/apollo.js#L34)

**Comment by TheCodeDestroyer** [comment]
@evans I'm quite sure this does not work at least it doesn't in `apollo-boost`:

> you can add them to the response before returning them from the map call, for example [here](https://github.com/benawad/slack-clone-client/blob/31_fix_auto_refresh_of_jwt_tokens/src/apollo.js#L34)
