### ISSUE TITLE
Compatibility issue with IE 11

### ISSUE THREAD

**Issue by cody-walker-ck** [apollographql/apollo-link#38]
zenObservable makes use of the Symbol data type which is not supported in IE 11.

**Intended outcome:**

Including apollo-client >= 1.9.0 in another repo works for all browsers except IE 11.

**Actual outcome:**

In IE 11 the script fails on page load. The browser doesn't support the Symbol constructor.
![IE Error](https://user-images.githubusercontent.com/28712098/29096379-8c9866d4-7c49-11e7-9b66-4b64755953e4.png)

**How to reproduce the issue:**

Running any app which depends on apollo-link or apollo-client >= 1.9.0 should cause the error immediately on page load.

**Comment by evanshauser** [comment]
@cody-walker-ck Thank you so much for bring this up with an issue! I removed Symbol from `zen-obervable-ts`, so things should work with IE11. Please let us know if you run into anything more.
