### ISSUE TITLE
Example for implementing live queries

### ISSUE THREAD

**Issue by azazdeaz** [apollographql/apollo-link#381]
I spent a lot of time trying to implement live queries but i always ran into some issue and i just realized that i should ask if there is a suggested way to do it :)

What i need is to track the live queries and update them manually when i get an update from a custom ws server.

(i'm using react-apollo)
```
    "react-apollo": "^2.0.4",
    "apollo-cache-inmemory": "^1.1.4",
    "apollo-client": "^2.0.4",
    "apollo-link": "^1.0.7",
    "apollo-link-batch-http": "^1.0.4",
    "apollo-link-dedup": "^1.0.5",
    "apollo-link-error": "^1.0.1",
    "apollo-link-http": "^1.3.2",
    "apollo-server-express": "^1.2.0",
```

I tried with apollo link:
https://gist.github.com/azazdeaz/32050e0cd051c58805d3bf49c8244708
 - parse live directives
 - subscribe to my custom updates
 - refetch the query on any update ([like in polling-link](https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-polling/src/pollingLink.ts#L42))
 - unsubscribe on complete callback ([like in polling-link](https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-polling/src/pollingLink.ts#L56))

My issues were:
 - sometimes complete callback was called before the component unmounted
 - or complete callback was not called after the component unmounted

Unfortunately, after days of reading the source, i wasn't able to find out how things should work and where is it going wrong, so it would be super helpful to have a minimal example about how it should be done :)

**Comment by azazdeaz** [comment]
Ie., would it be possible to hook into the QueryManager to monitor all the live queries?

**Comment by azazdeaz** [comment]
For now, i just put an extra HOC between my React components and the react-apollo/graphql HOC where i do the same things i mentioned above.
Not the nicest solution but at least i can reliably know when should i start and stop listen to the updates of a query (from mount/unmount callbacks of the component).

**Comment by JoviDeCroock** [comment]
Since this issue is really outdated I am closing it but if you are still concerned about this feel free to reopen and I'll get back to you asap.
