### ISSUE TITLE
link fallback pipeline

### ISSUE THREAD

**Issue by nripendra** [apollographql/apollo-link#396]
Is there a way to create a fallback pipeline of link? Here's what I want to do:

- First query locally (localstorage). [apollographql/apollo-link-state](https://github.com/apollographql/apollo-link-state) can be used here.
- If the data is not available locally then pull data using http-link.

Is there any easy way to do this?

**Comment by evans** [comment]
Good question! We are planning to create `race` sends two requests in parallel and then returns the first successful one. In the meantime, you could create a split of http and state, then change the context depending on the return value
