### ISSUE TITLE
SyntaxError: Unexpected token H in JSON at position 0

### ISSUE THREAD

**Issue by ash0080** [apollographql/apollo-link#415]
onError(({ graphQLErrors, networkError }))
 the networkError.bodyText is a Non standard JSON String

```
"HttpQueryError: {"errors":[{"message":"Unknown argument \"openId2\" on field \"loginWechat\" of type \"Query\". Did you mean \"openId\"?","locations":[{"line":2,"column":15}]},{"message":"Field \"loginWechat\" argument \"openId\" of type \"String!\" is required but not provided.","locations":[{"line":2,"column":3}]}]}"

```
This should be a bug

**Comment by clementi** [comment]
👍

**Comment by romain-web** [comment]
do you find a solution alone ? I have a similar problem,

<img width="704" alt="capture d ecran 2018-02-28 a 18 47 29" src="https://user-images.githubusercontent.com/823314/36803465-e62dfad8-1cb7-11e8-98a7-d3fee6e79128.png">

<img width="296" alt="capture d ecran 2018-02-28 a 18 48 05" src="https://user-images.githubusercontent.com/823314/36803481-f33f5ba4-1cb7-11e8-88f1-ebfb470f0fe0.png">

in the network I see the correct body in the response but HttpLink cannot find it (`bodyText = null`)

**Comment by ash0080** [comment]
@romain-web 
99%, that is because the name of your query or mutation case is wrong, the graphql can not find the named operation.
plz check it the uppercase or lowercase
