### ISSUE TITLE
Feature Idea (apollo-link-retry):  attempt "fix" before scheduling retries

### ISSUE THREAD

**Issue by kiran-sonnad-ck** [apollographql/apollo-link#433]
In some error cases, there are ways to address the error before attempting a retry. For example, a `401` might be the result of an expired access token that could be refreshed before retrying.

The user could provide a function that would be called prior to scheduling a retry in order to attempt a fix. The fix might be async, so callback or Promises would be required. If the promise resolves (or callback is invoked), scheduling the retry can proceed. Passing the same options that `retryIf` gets would be helpful in case they only want to try on the first retry attempt, or only for certain errors.

**Comment by pho3nixf1re** [comment]
Why not just convert `retryIf` to support a promise? Is there a major technical hurdle involved with that?

**Comment by pho3nixf1re** [comment]
It seems that this section here need to support an optional promise callback to wait on if it is going to retry. Currently all it does is schedule a timeout... Maybe we could provide a custom retry callback instead? That may be the easiest.

https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-retry/src/retryLink.ts#L147-L172

**Comment by kiran-sonnad-ck** [comment]
Adding Promise support to `retryIf` would certainly work, I just wasn't sure whether it might be overloading that function too much (from an API perspective). It's definitely the minimal solution though.

I also hacked together a local version that supports a new `fix` function option that is called before `scheduleRetry`.

**Comment by pho3nixf1re** [comment]
Do you have a branch I can compare with @kiran-sonnad-ck ? I'm working on a fork and PR as a request for comment implementation. I tried implementing my own link for this but it's buggy. We need this pretty quickly so I'm willing to take on the task of seeing this through.

**Comment by kiran-sonnad-ck** [comment]
I'll open a PR that we can work on.

**Comment by evans** [comment]
We merged in #436 and published in 2.2.0 Thank you @ksonnad for adding the ability to use promises in `retryIf`!
