### ISSUE TITLE
Use Apollo Link to bypass caching on disk: feature idea

### ISSUE THREAD

**Issue by sepehr500** [apollographql/apollo-link#45]
Hello. I am using Apollo Client on a project that has deals with a lot of sensitive user data, so can not store any information on cache/disk. It would be great if we could use Apollo Link to not write to the cache by default.

**Comment by stubailo** [comment]
> Hello. I am using Apollo Client on a project that has deals with a lot of sensitive user data, so can not store any information on cache/disk.

Apollo Client doesn't cache any data on disk. If you can put it in React, you can put it in Apollo Client - no difference there.

**Comment by sepehr500** [comment]
Thanks! I was a little confused about what was meant by "caching"

**Comment by stubailo** [comment]
Yeah - it mostly means storing data in a variable, much like redux
