### ISSUE TITLE
apollo-link-dedup not working when component is unmounted

### ISSUE THREAD

**Issue by Rockson** [apollographql/apollo-link#460]
**Intended outcome:**
I expect apollo client not to send the same query to the server even when ComponentA( who was sending the same query of ComponentB) is unmounted

**Actual outcome:**
It send the same query 2 times

**How to reproduce the issue:**

Actually i've tried this with the same Component:
I mount the _ComponentA_ using react router, then apollo send the query to the server.
I've set a delay to the server response so it lasts 10 seconds.
On the client i change route before the 10 seconds ends, then i go back to the previous route where it renders _ComponentA_ but Apollo client sends another request to the server. I dont' think this should be right

I actually noted that even if _ComponentA_ will unmount before getting the actual response from the server, in the background ApolloClient won't cancel the request but it will update the store as soon as it gets the response from server.

**Comment by JoviDeCroock** [comment]
Since this issue is really outdated I am closing it but if you are still concerned about this feel free to reopen and I'll get back to you asap.
