### ISSUE TITLE
Long running mutation appears to be retried after 2 minutes

### ISSUE THREAD

**Issue by daviestar** [apollographql/apollo-link#464]
Hello,

I have a long running import script (~4 minutes) which is kicked off with a graphql mutation, and I've noticed that exactly 2 minutes after I trigger my mutation, it gets retried, causing the import to be run twice.  I've been looking through the code on here but haven't been able to find the relevant functionality to turn it off.

I'm putting this as an issue as it should be documented IMO.

My setup:
```js
import ApolloClient from 'apollo-client'
import { ApolloLink } from 'apollo-link'
import { createHttpLink } from 'apollo-link-http'
import { InMemoryCache } from 'apollo-cache-inmemory'
import config from 'src/config'
import { getItem } from 'src/utils/local-store'

const httpLink = createHttpLink({ uri: config.graphql })
const middlewareLink = new ApolloLink((operation, forward) => {
  const token = getItem(config.jwtKey)
  if (token) {
    operation.setContext({
      headers: {
        Authorization: `Bearer ${token}`
      }
    })
  }
  return forward(operation)
})

const client = new ApolloClient({
  link: middlewareLink.concat(httpLink),
  cache: new InMemoryCache().restore(window.__APOLLO_STATE__ || {})
})

export default client
```

**Intended outcome:**
Mutation isn't retried without me asking it to, or it's documented how to change this behaviour

**Actual outcome:**
Mutation is retried after 2 minutes

Thanks.

**Comment by daviestar** [comment]
Apologies, after much hair-pulling I've discovered this was due to node's (in my case Koa) default timeout.. I didn't think this would automatically retry the request but... it does!

the fix was simply:
```js
// make timeout value 5 minutes
app.use(async (ctx, next) => {
  ctx.req.setTimeout(5 * 60 * 1000)
  await next()
})
```
Cheers.

**Comment by babsonmatt** [comment]
@daviestar I'm encountering the same issue here, using koa as well, however I believe koa is not the cause of the duplicate request.

If you try to replicate the request using curl or something similar (right click the network request in dev tools -> copy as curl) I think you'll find that the duplicate requests don't occur... leading me to believe it's definitely apollo related.

Any chance you could confirm the same?

Thanks!

**Comment by babsonmatt** [comment]
Spoke to soon, the issue seems to happen with fetch as well, so not an Apollo issue after all!

**Comment by daviestar** [comment]
The real solution to this problem is graphql subscriptions.

I just updated my importing UI with an import queue with various progress bars and subtasks as things are queued up and completed during the import.. pretty snazzy but did take a while to get right.

**Comment by babsonmatt** [comment]
@daviestar I was just commenting in regards to the retry, its actually a browser level implementation (so it's chrome etc initiating the retry).  I agree with what you said, definitely shouldnt be waiting that long for a request, just wanted to add some clarification to the issue itself and the whole retry phenomenon.

**Comment by daviestar** [comment]
For me, there was no 2nd network request logged in chrome devtools network tab, and the Koa timeout I mentioned above did fix the problem.  You can also completely turn the timeout off by setting it to `0`.
