### ISSUE TITLE
"TypeError: forward(...).flatMap is not a function" with apollo-link 1.1.0.

### ISSUE THREAD

**Issue by pleunv** [apollographql/apollo-link#476]
Hey guys!

We've got a custom middleware that takes a mutation operation and keeps it in a queue for an undetermined amount of time. The use-case is a CQRS-style task-based command API where confirmations are received asynchronously through a websocket, instead of "synchronously" as mutation response. The code looks something like this:

```js
return forward(operation).flatMap(response =>
  new Observable(observer => {
    putInQueueUntilWeReceiveConfirmation(response).then(observer.next).then(observer.complete);
  })
);
```

Up until `1.0.7` this worked fine, however, starting from `1.1.0` this is throwing a `TypeError: forward(...).flatMap is not a function` exception. Did anything change with the way operation observables are passed? I can't seem to find anything in the changelog.

Downgrading `apollo-link` to `1.0.7` fixes this issue, so it is definitely introduced in `1.1.0`.

**Comment by evans** [comment]
Thank you for opening the issue! It looks like [zen-observable](https://github.com/zenparsing/zen-observable/commit/46ab55f11f779beb497232e3f88fb12c42fbabf9) is modifying their API, so we're looking at switching or pinning the dependency

**Comment by evans** [comment]
Looks like `flatMap` is added back experimentally in this [commit](https://github.com/zenparsing/zen-observable/commit/46ab55f11f779beb497232e3f88fb12c42fbabf9). I'll leave this issue open until it's added back in

**Comment by pleunv** [comment]
I guess there's currently no workaround for this issue?

**Comment by JoviDeCroock** [comment]
Since this issue is really outdated I am closing it but if you are still concerned about this feel free to reopen and I'll get back to you asap.
