### ISSUE TITLE
Websocket support in Android API < 20

### ISSUE THREAD

**Issue by perrosnk** [apollographql/apollo-link#481]
I am not able to connect to the server by using apollo-link-ws when running android api < 20. It works fine in newer versions and iOS though.
Are older versions not supported or am I doing something something wrong?

**Comment by evans** [comment]
Thank you for the issue! apollo-link-ws uses [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws). Can you open an issue there with a reproduction repo?

**Comment by perrosnk** [comment]
First of all I wanted to be sure that it wasn't only me experiencing this. Are you seeing the same issue too?

**Comment by evans** [comment]
We don't currently test Android, so possibly. If you create a repository that reproduces the issue, then we can investigate. Let's move discussion to the subscription-transport
