### ISSUE TITLE
credentials option not working in apollo-link-batch-http 

### ISSUE THREAD

**Issue by Morantron** [apollographql/apollo-link#509]
**Intended outcome:** `credentials` option should work when using `apollo-link-batch-http`. If graphql is behind basic http auth for example, `credentials: "same-origin"` should propagate credentials.

**Actual outcome:** Credentials are not being propagate, getting a HTTP 401 response code.

**How to reproduce the issue:**

See repo https://github.com/Morantron/apollo-link-batch-http-credentials-bug

**Comment by evans** [comment]
We just published a new version of `apollo-link-batch-http`. Can you confirm the issue is still present?

**Comment by Morantron** [comment]
Awesome! It's fixed now on 1.1.0 version, thanks! :tada: :raised_hands:
