### ISSUE TITLE
Error when building with v1.2.0: "@types/zen-observable/index has no default export"

### ISSUE THREAD

**Issue by chenkie** [apollographql/apollo-link#511]
**Intended outcome:**

Build Angular CLI project with apollo-link. Looks like the latest release has issues with types/zen-observable

**Actual outcome:**

Got this error: 

```bash
ERROR in node_modules/apollo-link-context/node_modules/apollo-link/lib/types.d.ts(2,8): error
TS1192: Module '"/tmp/build_6e1e79a9d4e4cc0fceeda16a93512a8c/node_modules/@types/zen
observable/index"' has no default export.
```

**How to reproduce the issue:**

Typical Angular CLI setup with apollo-client v2.2.5 and apollo-angular v1.0.1. Only happens with apollo-link v1.2.0

**Comment by lirbank** [comment]
I have the same issue, using create-react-app.

**Comment by yihuaf** [comment]
`graphql-tools` also affected by the aforementioned version of `apollo-link`.

**Comment by yihuaf** [comment]
Following this PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23725, adding `"allowSyntheticDefaultImports": true` to `tsconfig.json` fixed the issue for me.

**Comment by neural22** [comment]
Same issue here! solution proposed by @yihuaf didn't work for us.

**Comment by neural22** [comment]
This is currently our tsconfig.json file, does someone have an idea?
`{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  }
}`

**Comment by lceck27** [comment]
I have the same issue.

**Comment by akab** [comment]
Same issue. Solution proposed by @yihuaf didn't work, also tried with esModuleInterop = true.

**Comment by GiuRossi90** [comment]
I have the same issue!

**Comment by neural22** [comment]
Ok, we fixed the problem considering this ( https://stackoverflow.com/questions/43136859/angular-cli-ignores-tsconfig-json ) and adding the option allowSyntheticDefaultImports in the right file (tsconfig.app.json instead of tsconfig.json )

**Comment by vic08** [comment]
adding `allowSyntheticDefaultImports` to `tsconfig.json` helped in my case (using webpack with babel and ts-loader)

**Comment by davidnguyen179** [comment]
adding `"allowSyntheticDefaultImports": true` to `tsconfig.json` worked for me. But I think using 

```js
import * as Observable from 'zen-observable';
```
is better than 

```js
import Observable from 'zen-observable';
```
to files:
node_modules/apollo-link/lib/index.d.ts
node_modules/apollo-link/lib/link.d.ts
node_modules/apollo-link/lib/linkUtils.d.ts
node_modules/apollo-link/lib/types.d.ts

**Comment by dwaynelavon** [comment]
I added `"allowSyntheticDefaultImports": true` to tsconfig.json and it caused more errors for my application. My Jest/Enzyme tests broke with that option enabled. Any other solutions??

**Comment by davidnguyen179** [comment]
hi @dwaynelavon,

The reason for this problem is related to 

```js
node_modules/apollo-link/lib/index.d.ts
node_modules/apollo-link/lib/link.d.ts
node_modules/apollo-link/lib/linkUtils.d.ts
node_modules/apollo-link/lib/types.d.ts
```

They are using

```js
import Observable from 'zen-observable';
```

instead of 
```js
import * as Observable from 'zen-observable';
```

So the temporary solution is that you can fork this to your machine and change the code like the suggestion above.

**Comment by yihuaf** [comment]
By the way, this seems to be not only the latest version. I tried to roll back and the same problem is there as well.

**Comment by benjamn** [comment]
I don't think the namespace import (`import * as Observable ...`) makes sense, because the namespace is always an object, whereas `Observable` is supposed to be a constructor function. Please don't use `import * as Observable from "zen-observable"` or tell others to do the same. Instead, I would recommend waiting for the `zen-observable-ts` wrapper package that @evans has been working on: https://github.com/apollographql/apollo-link/pull/515

**Comment by lirbank** [comment]
I agree with @chenkie this issue is around v1.2.0 of apollo-link. If I force apollo-link to 1.1.0 - and set apollo-link-http to 1.3.3 (since that's the last version of apollo-http-ling being compatible with apollo-link 1.2.0, everything works.

```
{
  "dependencies": {
    "apollo-link-http": "1.3.3"
    ...
  },
    ...
  "resolutions": {
    "apollo-link": "1.1.0"
  }
}
```
