### ISSUE TITLE
Queries aren't working: apollo-link-http is calling fetcher with wrong arguments

### ISSUE THREAD

**Issue by kamranayub** [apollographql/apollo-link#514]
Using:

```
    "apollo-cache-inmemory": "1.1.9",
    "apollo-client": "2.2.5",
    "apollo-fetch": "0.7.0",
    "apollo-link-batch-http": "1.1.0",
    "apollo-link-http": "1.4.0",
```

Queries are not working at all. I am not sure if it's due to wrong package combinations but these should be the latest as of this issue.

**Intended outcome:**

Performing a query should return results

**Actual outcome:**

GraphQL server responds 400 Bad Request because POST has an empty body.

**How to reproduce the issue:**

This call in apollo-link-http is calling `fetcher(uri, options)`:

https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-http/src/httpLink.ts#L137

Whereas the fetcher accepts a single argument object for options:

https://github.com/apollographql/apollo-fetch/blob/master/packages/apollo-fetch/src/apollo-fetch.ts#L122

So as far as I can tell, the POST is blank.

**Comment by kamranayub** [comment]
My bad! It appears I had an outdated package that was being included in my bundle--with these package versions and properly bundled, it IS working. Sorry.

**Comment by LoicMahieu** [comment]
I get the same error. All dependencies are up-to-date... Which dependency wasn't updated for you ?

**Comment by LoicMahieu** [comment]
Fixed it by remove the `fetch` options:

Before:
```js
import { createApolloFetch } from 'apollo-fetch'
const fetch = createApolloFetch({
  uri: '/api/graphql/graphql'
})
const link = new BatchHttpLink({ fetch })
````

After:
```js
const link = new BatchHttpLink({ uri: '/api/graphql/graphql' })
```

For info, `apollo-fetch` version is `0.7.0`.

**Comment by kamranayub** [comment]
This is what my initialization looks like:

```
this.apolloClient = new ApolloClient({
      link: new BatchHttpLink({
        uri: graphqlUrl,
        credentials: "same-origin",
        batchMax,
        batchInterval
      }),
      cache: new InMemoryCache()
    });
```
