### ISSUE TITLE
BatchHttpLink does not add HTTP Response to context

### ISSUE THREAD

**Issue by therealtbs** [apollographql/apollo-link#550]
**Expected Behavior**
Consistent behavior with HttpLink by exposing the complete HTTP response through `context.response`

**Actual Behavior**
`context.response` is the response body and not the full HTTP response

**A _simple_ reproduction**
https://codesandbox.io/s/0q95olj22l
This will make a simple request to the SWAPI (https://graphiql.graphcms.com/simple/v1/swapi) using both HttpLink and BatchHttpLink and log the context.

**Issue Labels**

- [x] has-reproduction
- [ ] feature
- [ ] docs
- [ ] blocking
- [ ] good first issue

**Comment by rterysen** [comment]
I am having the same problem!  
https://github.com/apollographql/apollo-link/issues/631
