### ISSUE TITLE
[Feature request] Add a "onFailure" method to apollo-link-retry

### ISSUE THREAD

**Issue by baldurh** [apollographql/apollo-link#640]
I would love if there were a method that would be called if all the retries fail. I’m using `apollo-link-retry` for retrying when I get a 401 back from some request. The refresh token implementation we’re using is rather flaky so sometimes I get a refreshed token and am able to do a successful request on the retry. But sometimes that fails and I’m left with an unauthorised user. In that case I would want to force the user to log back in. So having a method which is called after all the retries fail would be really helpful.

**Comment by evans** [comment]
Try the using `apollo-link-error`'s new ability to retry a request once with an updated token. You can find the docs [here](https://www.apollographql.com/docs/link/links/error.html#retry-request)

Your link chain would look like:
error > retry > http
