### ISSUE TITLE
setContext does not work

### ISSUE THREAD

**Issue by tomitrescak** [apollographql/apollo-link#67]
**Intended outcome:**

I'm trying to add jwt token to authorisation.

**Actual outcome:**

No token is in the header

**How to reproduce the issue:**

```js
let uri = 'http://localhost:3000/graphql';

const setContext = (context: any) => ({
  ...context,
  headers: {
    ...context.headers,
    authorization: localStorage.getItem('jwtToken'),
  },
});

const link: any = ApolloLink.from([
  new SetContextLink(setContext),
  new BatchHttpLink({ uri, batchInterval: 50 }),
]);

export const apolloCache = new InMemoryCache(window.__APOLLO_STATE_);

client = new ApolloClient({
  cache: apolloCache,
  link
});
```

**Comment by tomitrescak** [comment]
these are the headers ... no matter what I put to setContext, it does not appear in the request. Yet, I am sure it is called when I put breakpoint there.

<img width="396" alt="screen shot 2017-09-07 at 8 39 06 pm" src="https://user-images.githubusercontent.com/2682705/30159675-bbd6e2ba-940c-11e7-8901-9d4acfac3723.png">

**Comment by tomitrescak** [comment]
Yes, you have a bug in BatchHttpLink and I have submitted a pull request #68

**Comment by jbaxleyiii** [comment]
This should be fixed! Thanks!
