### ISSUE TITLE
Update to @types/graphql@0.13

### ISSUE THREAD

**Issue by Yogu** [apollographql/apollo-link#717]
apollo-link declares `graphql` as a `peerDependency` that allows version 0.13, but it uses `@types/graphql@0.12` for its typings, which are incompatible to `@types/graphql@0.13`. It would be good to either update the types or specify them as `peerDependencies` so that users can bring their own type version if apollo is compatible with multiple versions. Either way, this is probably a breaking change.

**Comment by victorandree** [comment]
There are open PRs for this. See #743 for updating types or #735 for changing to a dev dependency.

**Comment by JoviDeCroock** [comment]
Since this is fine now, I suppose this can be closed
