### ISSUE TITLE
BatchHttpLink ignores `uri` parameter

### ISSUE THREAD

**Issue by AndrewRayCode** [apollographql/apollo-link#751]
According to [the docs](https://www.npmjs.com/package/apollo-link-batch-http):

 > const link = new BatchHttpLink({ uri: "/graphql" });

Except

```jsx
import ApolloClient from 'apollo-boost';
import { BatchHttpLink } from 'apollo-link-batch-http';

...

  const link = new BatchHttpLink({
    batchInterval: 10,
    credentials: 'include',
    uri: 'http://localhost:3000/some-thing',
  });

  const client = new ApolloClient({
    link,
  });
```

But this information is discarded, and all requests are made to
```jsx
http://localhost:3001/graphql
```

**Comment by maartenvanvliet** [comment]
Same thing happened to me when trying to use `createPersistedQueryLink` 

It happens when I use ApolloClient from `apollo-boost` but not if I use ApolloClient from `apollo-client`.

**Comment by polizz** [comment]
Ran into this as well with httpLink - apollo-boost ignores the link config option altogether. Maybe the docs could highlight this a little better? It is very easy to move between examples that gloss over this difference.

**Comment by swillis12** [comment]
Having the same issue using the client from `apollo-boost`. Is this unsupported?

**Comment by JoviDeCroock** [comment]
Apollo-boost does not seem to allow for providing your own link, I think this issue is more suited there. https://github.com/apollographql/apollo-client/blob/master/packages/apollo-boost/src/index.ts
