### ISSUE TITLE
Publish new version of apollo-link-retry

### ISSUE THREAD

**Issue by samdenty** [apollographql/apollo-link#752]
**Expected Behavior**

`@types/node` doesn't clash with `@types/zen-observable`

**Actual Behavior**

`@types/node` clashes with `@types/zen-observable`. Fixed in the latest type definitions (already upgraded on master).

Hasn't been published on NPM yet (https://unpkg.com/apollo-link-retry@2.2.4/package.json)

**Comment by BertrandFritsch** [comment]
+1
