### ISSUE TITLE
ApolloLink.from([]) return an instance of Observable instead of an instance of ApolloLink

### ISSUE THREAD

**Issue by Aetherall** [apollographql/apollo-link#77]
Hi!

I wanted to create a custom link
````javascript
const link = ApolloLink.from([new RetryLink(), new HttpLink({ uri: graphqlEndpoint })]);
````
to use it in my Apollo Client 
````javascript
const client = new ApolloClient({
	ssrMode: true,
	networkInterface: link,
	cache,
});
````

but my network Interface fails this check
````javascript
if (networkInterface instanceof ApolloLink) { ...
````

when I lookup the instanceof link, I get Observable

How should I proceed to turn this observable into an ApolloLink ?

Thanks !

**Comment by PCreations** [comment]
Are you sure of that ? Looking to the code of `ApolloLink.from` it doesn't seem possible. Are you looking to the right thing ? For me the problem was that the `ApolloLink` instance refers to the wrong declaration, but I do have an ApolloLink back from `ApolloLink.from`.

**Comment by Aetherall** [comment]
My bad, I was using the old ApolloClient from 'react-apollo' ><
