### ISSUE TITLE
Incorrect peer dependency warning

### ISSUE THREAD

**Issue by burck1** [apollographql/apollo-link#78]
**Intended outcome:**
Using the apollo-link-core npm package

**Actual outcome:**
Received a warning on install of the npm package

> warning "graphql-tag@2.4.2" has incorrect peer dependency "graphql@^0.9.0 || ^0.10.0".

**How to reproduce the issue:**
Make sure you have _yarn_ installed: https://yarnpkg.com/en/docs/install
(It looks like _npm_ does not verify peer dependencies?)

```
> mkdir test
> cd test
> yarn init -y
> yarn add apollo-link-core
...
warning "graphql-tag@2.4.2" has incorrect peer dependency "graphql@^0.9.0 || ^0.10.0".
...
```

**Comment by jbaxleyiii** [comment]
I'm going to move graphql to a peer dep which will fix this!

**Comment by burck1** [comment]
Awesome!

**Comment by jbaxleyiii** [comment]
done via https://github.com/apollographql/apollo-link/pull/144

**Comment by ash0080** [comment]
apollo-link-http@1.3.2

**Comment by Northshoot** [comment]
seems like bug resurfaced. Getting same error.

**Comment by danilomiranda** [comment]
Same here :(

**Comment by ShunnyBunny** [comment]
Same here. Do I need to add this dependency?
