### ISSUE TITLE
ApolloLink not actually used in first example in README

### ISSUE THREAD

**Issue by sdgluck** [apollographql/apollo-link#873]
Not a bug report or feature request. Just found it strange and a little confusing that in the first example of the ApolloLink documentation it is imported but never used?

This is the example:

```
import { ApolloLink } from 'apollo-link'; // <= imported, never used?
import { ApolloClient } from 'apollo-client';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { HttpLink } from 'apollo-link-http';

const client = new ApolloClient({
  link: new HttpLink({ uri: 'http://api.githunt.com/graphql' }),
  cache: new InMemoryCache()
});
```

(https://github.com/apollographql/apollo-link/blob/master/docs/source/index.md)

Thank you.

**Comment by JoviDeCroock** [comment]
Thanks for noticing this, I'll correct it :)
