### ISSUE TITLE
Release 1.5.6 causes CORS issues

### ISSUE THREAD

**Issue by gouegd** [apollographql/apollo-link#874]
**Expected Behavior**
Going from 1.5.5 to 1.5.6 does not introduce bugs

**Actual Behavior**
We started getting CORS issues with 1.5.6 because of new headers being present but not whitelisted on our server (apollographql-client-name, apollographql-client-version)

**A _simple_ reproduction**
Any request to the grqphQL endpoint fails if that endpoint is located on a different host (and thus requires proper CORS handling), while the new headers (introduced in 1.5.6) are not whitelisted by the GQL endpoint

The commit that causes this issue:
https://github.com/apollographql/apollo-link/commit/59b09f9bbcef1d4249a2557fabf28542e247d574

The problem is that even though we do not have `name` or `version` in our Apollo context, the headers are added with an undefined value.
Tests cover that the headers are added properly, but not that they should not be added in some (most) cases.

**Comment by gouegd** [comment]
Also when the issue is fixed (headers not sent when useless), this might be considered a major semver step, as folks may use these context values already and will wun into similar CORS issue. But that's your call :)

**Comment by hhff** [comment]
Just hit this against Shopify's GraphQL endpoint

**Comment by rocketraman** [comment]
Same problem here... we set up CORS at our ingress rather than set up via Apollo Server directly. Therefore, this was a breaking change for us.

**Comment by hwillson** [comment]
Sorry all - this was fixed in `apollo-link-http` 1.5.7. Thanks!
