### ISSUE TITLE
Typing errors at compile stage

### ISSUE THREAD

**Issue by OLDIN** [apollographql/apollo-link#889]
I installed the **"apollo-link-http": "^1.5.7"** package and see these errors during compilation:

![image](https://user-images.githubusercontent.com/15104330/50018880-6575b880-ffd9-11e8-9091-a574338159c0.png)

Because of this, I can't compile my project
I use typescript.

**Comment by hwillson** [comment]
@OLDIN you can fix this by adding `dom` to the `lib` section of your `tsconfig.json`:

```json
{
  "compilerOptions": {
    "lib": ["dom"]
  },
}
```
