### ISSUE TITLE
Is the payload sent to the server always an array type?

### ISSUE THREAD

**Issue by damiangreen** [apollographql/apollo-link#897]
Is the payload sent to the server always an array type?

I can't see this mentioned in the documentation and we'rs changing our back-end to support batching and need to make sure its not going to receive objects (e.g. if there is just one request)

**Comment by JoviDeCroock** [comment]
Right now it is always an array.

Issues here are reserved for bugs, but one of the following resources should help:

* Apollo Spectrum community: https://spectrum.chat/apollo
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests
