### ISSUE TITLE
apollographql-client-name is not set when using apollo-link-batch-http

### ISSUE THREAD

**Issue by nanandn** [apollographql/apollo-link#901]
When using apollo-link-batch-http, the apollographql-client-name and apollographql-client-version request headers are not set. I have 'name' and 'version' set in the apollo client configuration as per https://www.apollographql.com/docs/platform/client-awareness.html#Setup

These headers are set when using apollo-link-http

Anand

**Comment by JoviDeCroock** [comment]
Good spot, will check this as soon as possible.
