### ISSUE TITLE
Error in docs: `import HttpLink` instead of `import {HttpLink}`

### ISSUE THREAD

**Issue by vjpr** [apollographql/apollo-link#915]
https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-http#passing-context-per-query

```js
import HttpLink from "apollo-link-http";
import ApolloClient from "apollo-client";
import { InMemoryCache } from "apollo-cache-inmemory";
```

Conflicts with: https://www.apollographql.com/docs/link/index.html#apollo-client

**Comment by JoviDeCroock** [comment]
You are right, this should be the destructured output. I think this belongs with the docs repo for apollo-client though. Will see to bring this up there. 

Thanks for the remark! Feel free to PR it if you find the time.

**Comment by JoviDeCroock** [comment]
This should be resolved now, it uses the `createHttpLink` destructured import. Thanks for noticing this and telling.
