### ISSUE TITLE
Update peer dependency of Graphql

### ISSUE THREAD

**Issue by dauledk** [apollographql/apollo-link#929]
**Expected Behavior**
Install latest version of GraphQL without warnings

**Actual Behavior**
```
npm WARN apollo-link@1.2.2 requires a peer of graphql@^0.11.3 || ^0.12.3 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
```

**A _simple_ reproduction**
`npm i graphql@latest` in a repo with `apollo-link-context`

**Comment by hwillson** [comment]
@dauledk Which version of `apollo-link-context` are you using? The latest version (1.0.12) depends on `apollo-link` 1.2.6, which has been updated to accept a peer dep of `graphql` ^14.0.0.

**Comment by dauledk** [comment]
Sorry - I was being too fast 🤪 The previous package.json was not from the correct branch. It looks like this:
```
    "apollo-angular": "^1.5.0",
    "apollo-angular-link-http": "^1.4.0",
    "apollo-cache-inmemory": "^1.4.2",
    "apollo-client": "^2.4.12",
    "apollo-link-context": "^1.0.12",
    "apollo-link-error": "^1.1.5",
    "graphql": "^14.1.1",
    "graphql-tag": "^2.10.1",
```
This actually generates two warnings:

```
npm WARN apollo-link@1.2.2 requires a peer of graphql@^0.11.3 || ^0.12.3 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-extensions@0.1.2 requires a peer of graphql@0.10.x - 0.13.x but none is installed. You must install peer dependencies yourself.
```

So I already have the latest version of apollo-link-context.

**Comment by hwillson** [comment]
No problem - okay, I bet something else is pulling in the older `apollo-link` version then. Would you mind posting the output of `npm ls apollo-link`?

**Comment by dauledk** [comment]
Yeah: 

```
<full-path-to-my-project>
├─┬ apollo@1.9.2
│ ├── apollo-link@1.2.2
│ └─┬ apollo-link-http@1.5.5
│   ├── apollo-link@1.2.3
│   └─┬ apollo-link-http-common@0.2.5
│     └── apollo-link@1.2.3
├─┬ apollo-client@2.4.12
│ ├── apollo-link@1.2.2  deduped
│ └─┬ apollo-link-dedup@1.0.13
│   └── apollo-link@1.2.6
├─┬ apollo-link-context@1.0.12
│ └── apollo-link@1.2.6
└─┬ apollo-link-error@1.1.5
  ├── apollo-link@1.2.6
  └─┬ apollo-link-http-common@0.2.8
    └── apollo-link@1.2.6  deduped
```

**Comment by hwillson** [comment]
Okay - `apollo-client` has been updated to use the latest version, but those changes aren't being pushed out until `apollo-client` 2.5.0 is released next week. I'll ping the `apollo` tooling team about updating the link version that project is using. Thanks for reporting this!

**Comment by dauledk** [comment]
Is it safe to update GraphQl and ignore the warning - or should the warning be taken seriously 😄 ?

**Comment by hwillson** [comment]
Totally safe to ignore - all of the `apollo-` projects listed in that dep tree will work with `graphql` 14.

**Comment by JoviDeCroock** [comment]
Is it safe to say the dependency for graphql is no concern? 

It is supported in apollo-link: https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link/package.json#L44
