### ISSUE TITLE
npm install apollo-link-http results in No matching version found for apollo-link@^1.2.7

### ISSUE THREAD

**Issue by jwillia** [apollographql/apollo-link#931]
**Expected Behavior**
npm install apollo-link-http adds dep to package json and node_modules
**Actual Behavior**
No matching version found for apollo-link@^1.2.7

**A _simple_ reproduction**
npm install apollo-link-http anywhere

**Comment by daveybrown** [comment]
My duplicate issue is here with a little more info. [Is something wrong with 1.2.7 release tag?](https://github.com/apollographql/apollo-link/issues/932)
