### ISSUE TITLE
BatchHttpLink doesn't batch composed queries

### ISSUE THREAD

**Issue by ellioseven** [apollographql/apollo-link#962]
**Expected Behavior**

I expected queries are batched into a single request.

When using `BatchHttpLink`, qeruies created via `compose` and `graphql` from the `react-apollo` package don't seem to be batched. 

However, this does seem to work when using the `Query` component, I get a single HTTP request.

**Actual Behavior**

Instead, the queries cause multiple HTTP requests.

Are `compose` /  `graphql` HOC queries supported?

**A _simple_ reproduction**

https://gist.github.com/ellioseven/6b834656c55b9770461db21869eb138a

Here I am composing multiple GraphQL operations and then performing them on render. 

Stack:

```
"apollo-boost": "^0.3.0",
"apollo-link-batch-http": "^1.2.8",
"express": "^4.16.4",
"graphql": "^14.1.1",
"graphql-tag": "^2.10.1",
"isomorphic-unfetch": "^3.0.0",
"next": "^8.0.3",
"next-with-apollo": "^3.3.2",
"prop-types": "^15.7.2",
"react": "^16.8.3",
"react-apollo": "^2.5.0",
"react-dom": "^16.8.3"
```

**Comment by JoviDeCroock** [comment]
Hmm, for science could you try altering the batchInterval. Trying to see how compose could affect this.

**Comment by ellioseven** [comment]
@JoviDeCroock 

Interestingly, if I create a use composed component inside my "page", then it will work: https://gist.github.com/ellioseven/73d87bd4e7870e5f361926748fc67ca0

Perhaps this is an issue with my `next.js` integration?

```
// _app.js
import React from "react"
import App, { Container } from "next/app"
import { ApolloProvider } from "react-apollo"
import withApollo from "../util/apollo/withApollo"

class MyApp extends App {
  render () {
    const { Component, pageProps, apollo } = this.props
    return (
      <Container>
        <ApolloProvider client={ apollo }>
          <Component { ...pageProps } />
        </ApolloProvider>
      </Container>
    )
  }
}

export default withApollo(MyApp)
```

```
// withApollo.js
import withApollo from "next-with-apollo"
import { ApolloClient } from "apollo-client"
import { IntrospectionFragmentMatcher, InMemoryCache } from "apollo-boost"
import { BatchHttpLink } from "apollo-link-batch-http"

import types from "../../config/types.json"
import config from "../../config/apollo.config"

const fragmentMatcher = new IntrospectionFragmentMatcher({
  introspectionQueryResultData: types
})

const link = new BatchHttpLink({
  uri: config.endpoint,
  includeExtensions: true
})

const defaults = {}

const resolvers = {
  Mutation: {},
  Query: {}
}

export default withApollo(({ ctx, headers, initialState }) => {
  return new ApolloClient({
    cache: new InMemoryCache({ fragmentMatcher }).restore(initialState || {}),
    clientState: { defaults, resolvers },
    link
  })
})
```

I'll investigate a little further.

**Comment by ellioseven** [comment]
@JoviDeCroock Just to quickly add, I have tried various `batchInterval` timings to no avail.

**Comment by ellioseven** [comment]
I think I found the problem: https://github.com/apollographql/react-apollo/issues/698

Seems like batching doesn't work during SSR. Has anyone managed to find a way around this?

**Comment by ellioseven** [comment]
The only way I have managed to get around this is by replacing `graphql` with an array of `Query` components:

```
const GC = ({ children }) => {
  // Ensure query is made on SSR phase only.
  const fetchPolicy = () => typeof window === "undefined" ? "cache-first" : "cache-only"

  const operations = [
    { query: QUERY_GROUP_CONTENT, variables },
    { query: QUERY_GROUP_CONTENT_META, variables },
    { query: QUERY_MENU, variables: { name: config.menu[0] } },
    { query: QUERY_MENU, variables: { name: config.menu[1] } }
  ]

  const queries = operations.map(({ query, variables }) => (
    <Query
      query={ query }
      variables={ variables }
      fetchPolicy={ fetchPolicy() }
      children={ () => null } />
  ))

  return (
    <React.Fragment>
      { queries }
      { children }
    </React.Fragment>
  )
}
```

This isn't great, but from initial inspection, this performs a single request on SSR while there are zero requests on the frontend.

It feels like a bug to me that the batching works with `Query` components but not on `graphql` HOC components.

**Comment by JoviDeCroock** [comment]
When reasoning about this I realise why, React needs to know what to render as child of the next `graphql` HOC. This implies that it fires the Query and since it's in the SSR step I don't think this imposes that much hassle.

**Comment by JoviDeCroock** [comment]
Hey, is this a question you are still struggling with?
