### ISSUE TITLE
No matching version found for apollo-link@^1.2.11

### ISSUE THREAD

**Issue by brentluna** [apollographql/apollo-link#990]
**Expected Behavior**
That the package installs.

running `npm install` on my application
**Actual Behavior**

Breaks with:
```npm ERR! code ETARGET
npm ERR! notarget No matching version found for apollo-link@^1.2.11
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'apollo-link-schema'
npm ERR! notarget```

**Comment by brentluna** [comment]
I saw this has happened w/ versions in the past, and there was mention of having to republish the package.

**Comment by JoviDeCroock** [comment]
Could also be npm acting up, give it 10 minutes, otherwise I'll message around

**Comment by brentluna** [comment]
@JoviDeCroock I've been attempting for a couple hours now

**Comment by JoviDeCroock** [comment]
Also works in codesandbox, have you tried clearing your npm cache?

**Comment by brentluna** [comment]
Just attempted with 'npm cache clear --force` as well as deleting 'node_modules` and 'package-lock.json`, same error everytime

**Comment by JoviDeCroock** [comment]
Allright, will ping someone about it.

**Comment by brentluna** [comment]
So, after further digging, it may have to be with us using a non default registry. When removing the the registry from .npmrc it worked. Looking into that further

**Comment by JoviDeCroock** [comment]
Allright, so it's probably safe to close this issue I assume?

**Comment by brentluna** [comment]
Yeah. Sorry for buggin you, appreciate your assistance

**Comment by JoviDeCroock** [comment]
No problem and have a nice day!
